// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BidAsk.proto

package com.baidu.stock.quote.protocbuf;

public final class BidAskProto {
  private BidAskProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BidAskOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.baidu.stock.quote.protocbuf.BidAsk)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required float price = 1;</code>
     */
    boolean hasPrice();
    /**
     * <code>required float price = 1;</code>
     */
    float getPrice();

    /**
     * <code>optional int32 volume = 2;</code>
     */
    boolean hasVolume();
    /**
     * <code>optional int32 volume = 2;</code>
     */
    int getVolume();
  }
  /**
   * Protobuf type {@code com.baidu.stock.quote.protocbuf.BidAsk}
   */
  public static final class BidAsk extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.baidu.stock.quote.protocbuf.BidAsk)
      BidAskOrBuilder {
    // Use BidAsk.newBuilder() to construct.
    private BidAsk(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BidAsk(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BidAsk defaultInstance;
    public static BidAsk getDefaultInstance() {
      return defaultInstance;
    }

    public BidAsk getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BidAsk(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              price_ = input.readFloat();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              volume_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.baidu.stock.quote.protocbuf.BidAskProto.internal_static_com_baidu_stock_quote_protocbuf_BidAsk_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.baidu.stock.quote.protocbuf.BidAskProto.internal_static_com_baidu_stock_quote_protocbuf_BidAsk_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.baidu.stock.quote.protocbuf.BidAskProto.BidAsk.class, com.baidu.stock.quote.protocbuf.BidAskProto.BidAsk.Builder.class);
    }

    public static com.google.protobuf.Parser<BidAsk> PARSER =
        new com.google.protobuf.AbstractParser<BidAsk>() {
      public BidAsk parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BidAsk(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BidAsk> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PRICE_FIELD_NUMBER = 1;
    private float price_;
    /**
     * <code>required float price = 1;</code>
     */
    public boolean hasPrice() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required float price = 1;</code>
     */
    public float getPrice() {
      return price_;
    }

    public static final int VOLUME_FIELD_NUMBER = 2;
    private int volume_;
    /**
     * <code>optional int32 volume = 2;</code>
     */
    public boolean hasVolume() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 volume = 2;</code>
     */
    public int getVolume() {
      return volume_;
    }

    private void initFields() {
      price_ = 0F;
      volume_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPrice()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFloat(1, price_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, volume_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, price_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, volume_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.baidu.stock.quote.protocbuf.BidAskProto.BidAsk parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baidu.stock.quote.protocbuf.BidAskProto.BidAsk parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baidu.stock.quote.protocbuf.BidAskProto.BidAsk parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baidu.stock.quote.protocbuf.BidAskProto.BidAsk parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baidu.stock.quote.protocbuf.BidAskProto.BidAsk parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.baidu.stock.quote.protocbuf.BidAskProto.BidAsk parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.baidu.stock.quote.protocbuf.BidAskProto.BidAsk parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.baidu.stock.quote.protocbuf.BidAskProto.BidAsk parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.baidu.stock.quote.protocbuf.BidAskProto.BidAsk parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.baidu.stock.quote.protocbuf.BidAskProto.BidAsk parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.baidu.stock.quote.protocbuf.BidAskProto.BidAsk prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.baidu.stock.quote.protocbuf.BidAsk}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.baidu.stock.quote.protocbuf.BidAsk)
        com.baidu.stock.quote.protocbuf.BidAskProto.BidAskOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.baidu.stock.quote.protocbuf.BidAskProto.internal_static_com_baidu_stock_quote_protocbuf_BidAsk_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.baidu.stock.quote.protocbuf.BidAskProto.internal_static_com_baidu_stock_quote_protocbuf_BidAsk_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.baidu.stock.quote.protocbuf.BidAskProto.BidAsk.class, com.baidu.stock.quote.protocbuf.BidAskProto.BidAsk.Builder.class);
      }

      // Construct using com.baidu.stock.quote.protocbuf.BidAskProto.BidAsk.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        price_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000001);
        volume_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.baidu.stock.quote.protocbuf.BidAskProto.internal_static_com_baidu_stock_quote_protocbuf_BidAsk_descriptor;
      }

      public com.baidu.stock.quote.protocbuf.BidAskProto.BidAsk getDefaultInstanceForType() {
        return com.baidu.stock.quote.protocbuf.BidAskProto.BidAsk.getDefaultInstance();
      }

      public com.baidu.stock.quote.protocbuf.BidAskProto.BidAsk build() {
        com.baidu.stock.quote.protocbuf.BidAskProto.BidAsk result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.baidu.stock.quote.protocbuf.BidAskProto.BidAsk buildPartial() {
        com.baidu.stock.quote.protocbuf.BidAskProto.BidAsk result = new com.baidu.stock.quote.protocbuf.BidAskProto.BidAsk(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.price_ = price_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.volume_ = volume_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.baidu.stock.quote.protocbuf.BidAskProto.BidAsk) {
          return mergeFrom((com.baidu.stock.quote.protocbuf.BidAskProto.BidAsk)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.baidu.stock.quote.protocbuf.BidAskProto.BidAsk other) {
        if (other == com.baidu.stock.quote.protocbuf.BidAskProto.BidAsk.getDefaultInstance()) return this;
        if (other.hasPrice()) {
          setPrice(other.getPrice());
        }
        if (other.hasVolume()) {
          setVolume(other.getVolume());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPrice()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.baidu.stock.quote.protocbuf.BidAskProto.BidAsk parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.baidu.stock.quote.protocbuf.BidAskProto.BidAsk) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private float price_ ;
      /**
       * <code>required float price = 1;</code>
       */
      public boolean hasPrice() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required float price = 1;</code>
       */
      public float getPrice() {
        return price_;
      }
      /**
       * <code>required float price = 1;</code>
       */
      public Builder setPrice(float value) {
        bitField0_ |= 0x00000001;
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float price = 1;</code>
       */
      public Builder clearPrice() {
        bitField0_ = (bitField0_ & ~0x00000001);
        price_ = 0F;
        onChanged();
        return this;
      }

      private int volume_ ;
      /**
       * <code>optional int32 volume = 2;</code>
       */
      public boolean hasVolume() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 volume = 2;</code>
       */
      public int getVolume() {
        return volume_;
      }
      /**
       * <code>optional int32 volume = 2;</code>
       */
      public Builder setVolume(int value) {
        bitField0_ |= 0x00000002;
        volume_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 volume = 2;</code>
       */
      public Builder clearVolume() {
        bitField0_ = (bitField0_ & ~0x00000002);
        volume_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.baidu.stock.quote.protocbuf.BidAsk)
    }

    static {
      defaultInstance = new BidAsk(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.baidu.stock.quote.protocbuf.BidAsk)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_baidu_stock_quote_protocbuf_BidAsk_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_baidu_stock_quote_protocbuf_BidAsk_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014BidAsk.proto\022\037com.baidu.stock.quote.pr" +
      "otocbuf\"\'\n\006BidAsk\022\r\n\005price\030\001 \002(\002\022\016\n\006volu" +
      "me\030\002 \001(\005B.\n\037com.baidu.stock.quote.protoc" +
      "bufB\013BidAskProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_baidu_stock_quote_protocbuf_BidAsk_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_baidu_stock_quote_protocbuf_BidAsk_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_baidu_stock_quote_protocbuf_BidAsk_descriptor,
        new java.lang.String[] { "Price", "Volume", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
