// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BriefSnapShot.proto

package com.baidu.stock.quote.protocbuf;

public final class BriefSnapShotProto {
  private BriefSnapShotProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BriefSnapShotOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.baidu.stock.quote.protocbuf.BriefSnapShot)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string date = 1;</code>
     *
     * <pre>
     * 日期格式 yyyyMMdd
     * </pre>
     */
    boolean hasDate();
    /**
     * <code>required string date = 1;</code>
     *
     * <pre>
     * 日期格式 yyyyMMdd
     * </pre>
     */
    java.lang.String getDate();
    /**
     * <code>required string date = 1;</code>
     *
     * <pre>
     * 日期格式 yyyyMMdd
     * </pre>
     */
    com.google.protobuf.ByteString
        getDateBytes();

    /**
     * <code>required string time = 2;</code>
     *
     * <pre>
     * 时间格式 HHmmss
     * </pre>
     */
    boolean hasTime();
    /**
     * <code>required string time = 2;</code>
     *
     * <pre>
     * 时间格式 HHmmss
     * </pre>
     */
    java.lang.String getTime();
    /**
     * <code>required string time = 2;</code>
     *
     * <pre>
     * 时间格式 HHmmss
     * </pre>
     */
    com.google.protobuf.ByteString
        getTimeBytes();

    /**
     * <code>required .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
     *
     * <pre>
     * 股票信息
     * </pre>
     */
    boolean hasStockBasic();
    /**
     * <code>required .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
     *
     * <pre>
     * 股票信息
     * </pre>
     */
    com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic getStockBasic();
    /**
     * <code>required .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
     *
     * <pre>
     * 股票信息
     * </pre>
     */
    com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasicOrBuilder getStockBasicOrBuilder();

    /**
     * <code>optional float close = 4;</code>
     *
     * <pre>
     * 今收盘价
     * </pre>
     */
    boolean hasClose();
    /**
     * <code>optional float close = 4;</code>
     *
     * <pre>
     * 今收盘价
     * </pre>
     */
    float getClose();

    /**
     * <code>optional int64 volume = 5;</code>
     *
     * <pre>
     * 成交总量 (股)
     * </pre>
     */
    boolean hasVolume();
    /**
     * <code>optional int64 volume = 5;</code>
     *
     * <pre>
     * 成交总量 (股)
     * </pre>
     */
    long getVolume();

    /**
     * <code>optional double amount = 6;</code>
     *
     * <pre>
     * 成交金额 (元)
     * </pre>
     */
    boolean hasAmount();
    /**
     * <code>optional double amount = 6;</code>
     *
     * <pre>
     * 成交金额 (元)
     * </pre>
     */
    double getAmount();

    /**
     * <code>optional float netChange = 7;</code>
     *
     * <pre>
     * 涨跌额
     * </pre>
     */
    boolean hasNetChange();
    /**
     * <code>optional float netChange = 7;</code>
     *
     * <pre>
     * 涨跌额
     * </pre>
     */
    float getNetChange();

    /**
     * <code>optional float netChangeRatio = 8;</code>
     *
     * <pre>
     * 涨跌幅
     * </pre>
     */
    boolean hasNetChangeRatio();
    /**
     * <code>optional float netChangeRatio = 8;</code>
     *
     * <pre>
     * 涨跌幅
     * </pre>
     */
    float getNetChangeRatio();

    /**
     * <code>optional float amplitudeRatio = 9;</code>
     *
     * <pre>
     * 振幅
     * </pre>
     */
    boolean hasAmplitudeRatio();
    /**
     * <code>optional float amplitudeRatio = 9;</code>
     *
     * <pre>
     * 振幅
     * </pre>
     */
    float getAmplitudeRatio();

    /**
     * <code>optional float turnoverRatio = 10;</code>
     *
     * <pre>
     * 换手率
     * </pre>
     */
    boolean hasTurnoverRatio();
    /**
     * <code>optional float turnoverRatio = 10;</code>
     *
     * <pre>
     * 换手率
     * </pre>
     */
    float getTurnoverRatio();

    /**
     * <code>optional double currencyValue = 11;</code>
     *
     * <pre>
     * 流通市值
     * </pre>
     */
    boolean hasCurrencyValue();
    /**
     * <code>optional double currencyValue = 11;</code>
     *
     * <pre>
     * 流通市值
     * </pre>
     */
    double getCurrencyValue();

    /**
     * <code>optional double capitalization = 12;</code>
     *
     * <pre>
     * 总市值
     * </pre>
     */
    boolean hasCapitalization();
    /**
     * <code>optional double capitalization = 12;</code>
     *
     * <pre>
     * 总市值
     * </pre>
     */
    double getCapitalization();

    /**
     * <code>optional float lyrPeratio = 13;</code>
     *
     * <pre>
     * LYR市盈率
     * </pre>
     */
    boolean hasLyrPeratio();
    /**
     * <code>optional float lyrPeratio = 13;</code>
     *
     * <pre>
     * LYR市盈率
     * </pre>
     */
    float getLyrPeratio();

    /**
     * <code>optional float mrqPeratio = 14;</code>
     *
     * <pre>
     * mrq市盈率
     * </pre>
     */
    boolean hasMrqPeratio();
    /**
     * <code>optional float mrqPeratio = 14;</code>
     *
     * <pre>
     * mrq市盈率
     * </pre>
     */
    float getMrqPeratio();

    /**
     * <code>optional float ttmPeratio = 15;</code>
     *
     * <pre>
     * TTM市盈率
     * </pre>
     */
    boolean hasTtmPeratio();
    /**
     * <code>optional float ttmPeratio = 15;</code>
     *
     * <pre>
     * TTM市盈率
     * </pre>
     */
    float getTtmPeratio();
  }
  /**
   * Protobuf type {@code com.baidu.stock.quote.protocbuf.BriefSnapShot}
   */
  public static final class BriefSnapShot extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.baidu.stock.quote.protocbuf.BriefSnapShot)
      BriefSnapShotOrBuilder {
    // Use BriefSnapShot.newBuilder() to construct.
    private BriefSnapShot(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BriefSnapShot(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BriefSnapShot defaultInstance;
    public static BriefSnapShot getDefaultInstance() {
      return defaultInstance;
    }

    public BriefSnapShot getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BriefSnapShot(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              date_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              time_ = bs;
              break;
            }
            case 26: {
              com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = stockBasic_.toBuilder();
              }
              stockBasic_ = input.readMessage(com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(stockBasic_);
                stockBasic_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              close_ = input.readFloat();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              volume_ = input.readInt64();
              break;
            }
            case 49: {
              bitField0_ |= 0x00000020;
              amount_ = input.readDouble();
              break;
            }
            case 61: {
              bitField0_ |= 0x00000040;
              netChange_ = input.readFloat();
              break;
            }
            case 69: {
              bitField0_ |= 0x00000080;
              netChangeRatio_ = input.readFloat();
              break;
            }
            case 77: {
              bitField0_ |= 0x00000100;
              amplitudeRatio_ = input.readFloat();
              break;
            }
            case 85: {
              bitField0_ |= 0x00000200;
              turnoverRatio_ = input.readFloat();
              break;
            }
            case 89: {
              bitField0_ |= 0x00000400;
              currencyValue_ = input.readDouble();
              break;
            }
            case 97: {
              bitField0_ |= 0x00000800;
              capitalization_ = input.readDouble();
              break;
            }
            case 109: {
              bitField0_ |= 0x00001000;
              lyrPeratio_ = input.readFloat();
              break;
            }
            case 117: {
              bitField0_ |= 0x00002000;
              mrqPeratio_ = input.readFloat();
              break;
            }
            case 125: {
              bitField0_ |= 0x00004000;
              ttmPeratio_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.baidu.stock.quote.protocbuf.BriefSnapShotProto.internal_static_com_baidu_stock_quote_protocbuf_BriefSnapShot_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.baidu.stock.quote.protocbuf.BriefSnapShotProto.internal_static_com_baidu_stock_quote_protocbuf_BriefSnapShot_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.baidu.stock.quote.protocbuf.BriefSnapShotProto.BriefSnapShot.class, com.baidu.stock.quote.protocbuf.BriefSnapShotProto.BriefSnapShot.Builder.class);
    }

    public static com.google.protobuf.Parser<BriefSnapShot> PARSER =
        new com.google.protobuf.AbstractParser<BriefSnapShot>() {
      public BriefSnapShot parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BriefSnapShot(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BriefSnapShot> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int DATE_FIELD_NUMBER = 1;
    private java.lang.Object date_;
    /**
     * <code>required string date = 1;</code>
     *
     * <pre>
     * 日期格式 yyyyMMdd
     * </pre>
     */
    public boolean hasDate() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string date = 1;</code>
     *
     * <pre>
     * 日期格式 yyyyMMdd
     * </pre>
     */
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          date_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string date = 1;</code>
     *
     * <pre>
     * 日期格式 yyyyMMdd
     * </pre>
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 2;
    private java.lang.Object time_;
    /**
     * <code>required string time = 2;</code>
     *
     * <pre>
     * 时间格式 HHmmss
     * </pre>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string time = 2;</code>
     *
     * <pre>
     * 时间格式 HHmmss
     * </pre>
     */
    public java.lang.String getTime() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          time_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string time = 2;</code>
     *
     * <pre>
     * 时间格式 HHmmss
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTimeBytes() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STOCKBASIC_FIELD_NUMBER = 3;
    private com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic stockBasic_;
    /**
     * <code>required .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
     *
     * <pre>
     * 股票信息
     * </pre>
     */
    public boolean hasStockBasic() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
     *
     * <pre>
     * 股票信息
     * </pre>
     */
    public com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic getStockBasic() {
      return stockBasic_;
    }
    /**
     * <code>required .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
     *
     * <pre>
     * 股票信息
     * </pre>
     */
    public com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasicOrBuilder getStockBasicOrBuilder() {
      return stockBasic_;
    }

    public static final int CLOSE_FIELD_NUMBER = 4;
    private float close_;
    /**
     * <code>optional float close = 4;</code>
     *
     * <pre>
     * 今收盘价
     * </pre>
     */
    public boolean hasClose() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional float close = 4;</code>
     *
     * <pre>
     * 今收盘价
     * </pre>
     */
    public float getClose() {
      return close_;
    }

    public static final int VOLUME_FIELD_NUMBER = 5;
    private long volume_;
    /**
     * <code>optional int64 volume = 5;</code>
     *
     * <pre>
     * 成交总量 (股)
     * </pre>
     */
    public boolean hasVolume() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int64 volume = 5;</code>
     *
     * <pre>
     * 成交总量 (股)
     * </pre>
     */
    public long getVolume() {
      return volume_;
    }

    public static final int AMOUNT_FIELD_NUMBER = 6;
    private double amount_;
    /**
     * <code>optional double amount = 6;</code>
     *
     * <pre>
     * 成交金额 (元)
     * </pre>
     */
    public boolean hasAmount() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional double amount = 6;</code>
     *
     * <pre>
     * 成交金额 (元)
     * </pre>
     */
    public double getAmount() {
      return amount_;
    }

    public static final int NETCHANGE_FIELD_NUMBER = 7;
    private float netChange_;
    /**
     * <code>optional float netChange = 7;</code>
     *
     * <pre>
     * 涨跌额
     * </pre>
     */
    public boolean hasNetChange() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional float netChange = 7;</code>
     *
     * <pre>
     * 涨跌额
     * </pre>
     */
    public float getNetChange() {
      return netChange_;
    }

    public static final int NETCHANGERATIO_FIELD_NUMBER = 8;
    private float netChangeRatio_;
    /**
     * <code>optional float netChangeRatio = 8;</code>
     *
     * <pre>
     * 涨跌幅
     * </pre>
     */
    public boolean hasNetChangeRatio() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional float netChangeRatio = 8;</code>
     *
     * <pre>
     * 涨跌幅
     * </pre>
     */
    public float getNetChangeRatio() {
      return netChangeRatio_;
    }

    public static final int AMPLITUDERATIO_FIELD_NUMBER = 9;
    private float amplitudeRatio_;
    /**
     * <code>optional float amplitudeRatio = 9;</code>
     *
     * <pre>
     * 振幅
     * </pre>
     */
    public boolean hasAmplitudeRatio() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional float amplitudeRatio = 9;</code>
     *
     * <pre>
     * 振幅
     * </pre>
     */
    public float getAmplitudeRatio() {
      return amplitudeRatio_;
    }

    public static final int TURNOVERRATIO_FIELD_NUMBER = 10;
    private float turnoverRatio_;
    /**
     * <code>optional float turnoverRatio = 10;</code>
     *
     * <pre>
     * 换手率
     * </pre>
     */
    public boolean hasTurnoverRatio() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional float turnoverRatio = 10;</code>
     *
     * <pre>
     * 换手率
     * </pre>
     */
    public float getTurnoverRatio() {
      return turnoverRatio_;
    }

    public static final int CURRENCYVALUE_FIELD_NUMBER = 11;
    private double currencyValue_;
    /**
     * <code>optional double currencyValue = 11;</code>
     *
     * <pre>
     * 流通市值
     * </pre>
     */
    public boolean hasCurrencyValue() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional double currencyValue = 11;</code>
     *
     * <pre>
     * 流通市值
     * </pre>
     */
    public double getCurrencyValue() {
      return currencyValue_;
    }

    public static final int CAPITALIZATION_FIELD_NUMBER = 12;
    private double capitalization_;
    /**
     * <code>optional double capitalization = 12;</code>
     *
     * <pre>
     * 总市值
     * </pre>
     */
    public boolean hasCapitalization() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional double capitalization = 12;</code>
     *
     * <pre>
     * 总市值
     * </pre>
     */
    public double getCapitalization() {
      return capitalization_;
    }

    public static final int LYRPERATIO_FIELD_NUMBER = 13;
    private float lyrPeratio_;
    /**
     * <code>optional float lyrPeratio = 13;</code>
     *
     * <pre>
     * LYR市盈率
     * </pre>
     */
    public boolean hasLyrPeratio() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional float lyrPeratio = 13;</code>
     *
     * <pre>
     * LYR市盈率
     * </pre>
     */
    public float getLyrPeratio() {
      return lyrPeratio_;
    }

    public static final int MRQPERATIO_FIELD_NUMBER = 14;
    private float mrqPeratio_;
    /**
     * <code>optional float mrqPeratio = 14;</code>
     *
     * <pre>
     * mrq市盈率
     * </pre>
     */
    public boolean hasMrqPeratio() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>optional float mrqPeratio = 14;</code>
     *
     * <pre>
     * mrq市盈率
     * </pre>
     */
    public float getMrqPeratio() {
      return mrqPeratio_;
    }

    public static final int TTMPERATIO_FIELD_NUMBER = 15;
    private float ttmPeratio_;
    /**
     * <code>optional float ttmPeratio = 15;</code>
     *
     * <pre>
     * TTM市盈率
     * </pre>
     */
    public boolean hasTtmPeratio() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>optional float ttmPeratio = 15;</code>
     *
     * <pre>
     * TTM市盈率
     * </pre>
     */
    public float getTtmPeratio() {
      return ttmPeratio_;
    }

    private void initFields() {
      date_ = "";
      time_ = "";
      stockBasic_ = com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.getDefaultInstance();
      close_ = 0F;
      volume_ = 0L;
      amount_ = 0D;
      netChange_ = 0F;
      netChangeRatio_ = 0F;
      amplitudeRatio_ = 0F;
      turnoverRatio_ = 0F;
      currencyValue_ = 0D;
      capitalization_ = 0D;
      lyrPeratio_ = 0F;
      mrqPeratio_ = 0F;
      ttmPeratio_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStockBasic()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getStockBasic().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDateBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTimeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, stockBasic_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, close_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, volume_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeDouble(6, amount_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeFloat(7, netChange_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeFloat(8, netChangeRatio_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeFloat(9, amplitudeRatio_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeFloat(10, turnoverRatio_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeDouble(11, currencyValue_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeDouble(12, capitalization_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeFloat(13, lyrPeratio_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeFloat(14, mrqPeratio_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeFloat(15, ttmPeratio_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDateBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTimeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, stockBasic_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, close_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, volume_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, amount_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(7, netChange_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(8, netChangeRatio_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(9, amplitudeRatio_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(10, turnoverRatio_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(11, currencyValue_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(12, capitalization_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(13, lyrPeratio_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(14, mrqPeratio_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(15, ttmPeratio_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.baidu.stock.quote.protocbuf.BriefSnapShotProto.BriefSnapShot parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baidu.stock.quote.protocbuf.BriefSnapShotProto.BriefSnapShot parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baidu.stock.quote.protocbuf.BriefSnapShotProto.BriefSnapShot parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baidu.stock.quote.protocbuf.BriefSnapShotProto.BriefSnapShot parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baidu.stock.quote.protocbuf.BriefSnapShotProto.BriefSnapShot parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.baidu.stock.quote.protocbuf.BriefSnapShotProto.BriefSnapShot parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.baidu.stock.quote.protocbuf.BriefSnapShotProto.BriefSnapShot parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.baidu.stock.quote.protocbuf.BriefSnapShotProto.BriefSnapShot parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.baidu.stock.quote.protocbuf.BriefSnapShotProto.BriefSnapShot parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.baidu.stock.quote.protocbuf.BriefSnapShotProto.BriefSnapShot parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.baidu.stock.quote.protocbuf.BriefSnapShotProto.BriefSnapShot prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.baidu.stock.quote.protocbuf.BriefSnapShot}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.baidu.stock.quote.protocbuf.BriefSnapShot)
        com.baidu.stock.quote.protocbuf.BriefSnapShotProto.BriefSnapShotOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.baidu.stock.quote.protocbuf.BriefSnapShotProto.internal_static_com_baidu_stock_quote_protocbuf_BriefSnapShot_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.baidu.stock.quote.protocbuf.BriefSnapShotProto.internal_static_com_baidu_stock_quote_protocbuf_BriefSnapShot_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.baidu.stock.quote.protocbuf.BriefSnapShotProto.BriefSnapShot.class, com.baidu.stock.quote.protocbuf.BriefSnapShotProto.BriefSnapShot.Builder.class);
      }

      // Construct using com.baidu.stock.quote.protocbuf.BriefSnapShotProto.BriefSnapShot.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getStockBasicFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        date_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (stockBasicBuilder_ == null) {
          stockBasic_ = com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.getDefaultInstance();
        } else {
          stockBasicBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        close_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        volume_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        amount_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000020);
        netChange_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000040);
        netChangeRatio_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000080);
        amplitudeRatio_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000100);
        turnoverRatio_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000200);
        currencyValue_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000400);
        capitalization_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000800);
        lyrPeratio_ = 0F;
        bitField0_ = (bitField0_ & ~0x00001000);
        mrqPeratio_ = 0F;
        bitField0_ = (bitField0_ & ~0x00002000);
        ttmPeratio_ = 0F;
        bitField0_ = (bitField0_ & ~0x00004000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.baidu.stock.quote.protocbuf.BriefSnapShotProto.internal_static_com_baidu_stock_quote_protocbuf_BriefSnapShot_descriptor;
      }

      public com.baidu.stock.quote.protocbuf.BriefSnapShotProto.BriefSnapShot getDefaultInstanceForType() {
        return com.baidu.stock.quote.protocbuf.BriefSnapShotProto.BriefSnapShot.getDefaultInstance();
      }

      public com.baidu.stock.quote.protocbuf.BriefSnapShotProto.BriefSnapShot build() {
        com.baidu.stock.quote.protocbuf.BriefSnapShotProto.BriefSnapShot result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.baidu.stock.quote.protocbuf.BriefSnapShotProto.BriefSnapShot buildPartial() {
        com.baidu.stock.quote.protocbuf.BriefSnapShotProto.BriefSnapShot result = new com.baidu.stock.quote.protocbuf.BriefSnapShotProto.BriefSnapShot(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.date_ = date_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (stockBasicBuilder_ == null) {
          result.stockBasic_ = stockBasic_;
        } else {
          result.stockBasic_ = stockBasicBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.close_ = close_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.volume_ = volume_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.amount_ = amount_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.netChange_ = netChange_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.netChangeRatio_ = netChangeRatio_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.amplitudeRatio_ = amplitudeRatio_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.turnoverRatio_ = turnoverRatio_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.currencyValue_ = currencyValue_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.capitalization_ = capitalization_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.lyrPeratio_ = lyrPeratio_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.mrqPeratio_ = mrqPeratio_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.ttmPeratio_ = ttmPeratio_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.baidu.stock.quote.protocbuf.BriefSnapShotProto.BriefSnapShot) {
          return mergeFrom((com.baidu.stock.quote.protocbuf.BriefSnapShotProto.BriefSnapShot)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.baidu.stock.quote.protocbuf.BriefSnapShotProto.BriefSnapShot other) {
        if (other == com.baidu.stock.quote.protocbuf.BriefSnapShotProto.BriefSnapShot.getDefaultInstance()) return this;
        if (other.hasDate()) {
          bitField0_ |= 0x00000001;
          date_ = other.date_;
          onChanged();
        }
        if (other.hasTime()) {
          bitField0_ |= 0x00000002;
          time_ = other.time_;
          onChanged();
        }
        if (other.hasStockBasic()) {
          mergeStockBasic(other.getStockBasic());
        }
        if (other.hasClose()) {
          setClose(other.getClose());
        }
        if (other.hasVolume()) {
          setVolume(other.getVolume());
        }
        if (other.hasAmount()) {
          setAmount(other.getAmount());
        }
        if (other.hasNetChange()) {
          setNetChange(other.getNetChange());
        }
        if (other.hasNetChangeRatio()) {
          setNetChangeRatio(other.getNetChangeRatio());
        }
        if (other.hasAmplitudeRatio()) {
          setAmplitudeRatio(other.getAmplitudeRatio());
        }
        if (other.hasTurnoverRatio()) {
          setTurnoverRatio(other.getTurnoverRatio());
        }
        if (other.hasCurrencyValue()) {
          setCurrencyValue(other.getCurrencyValue());
        }
        if (other.hasCapitalization()) {
          setCapitalization(other.getCapitalization());
        }
        if (other.hasLyrPeratio()) {
          setLyrPeratio(other.getLyrPeratio());
        }
        if (other.hasMrqPeratio()) {
          setMrqPeratio(other.getMrqPeratio());
        }
        if (other.hasTtmPeratio()) {
          setTtmPeratio(other.getTtmPeratio());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDate()) {
          
          return false;
        }
        if (!hasTime()) {
          
          return false;
        }
        if (!hasStockBasic()) {
          
          return false;
        }
        if (!getStockBasic().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.baidu.stock.quote.protocbuf.BriefSnapShotProto.BriefSnapShot parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.baidu.stock.quote.protocbuf.BriefSnapShotProto.BriefSnapShot) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object date_ = "";
      /**
       * <code>required string date = 1;</code>
       *
       * <pre>
       * 日期格式 yyyyMMdd
       * </pre>
       */
      public boolean hasDate() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string date = 1;</code>
       *
       * <pre>
       * 日期格式 yyyyMMdd
       * </pre>
       */
      public java.lang.String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            date_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string date = 1;</code>
       *
       * <pre>
       * 日期格式 yyyyMMdd
       * </pre>
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        java.lang.Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string date = 1;</code>
       *
       * <pre>
       * 日期格式 yyyyMMdd
       * </pre>
       */
      public Builder setDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string date = 1;</code>
       *
       * <pre>
       * 日期格式 yyyyMMdd
       * </pre>
       */
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000001);
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      /**
       * <code>required string date = 1;</code>
       *
       * <pre>
       * 日期格式 yyyyMMdd
       * </pre>
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        date_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object time_ = "";
      /**
       * <code>required string time = 2;</code>
       *
       * <pre>
       * 时间格式 HHmmss
       * </pre>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string time = 2;</code>
       *
       * <pre>
       * 时间格式 HHmmss
       * </pre>
       */
      public java.lang.String getTime() {
        java.lang.Object ref = time_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            time_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string time = 2;</code>
       *
       * <pre>
       * 时间格式 HHmmss
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTimeBytes() {
        java.lang.Object ref = time_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          time_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string time = 2;</code>
       *
       * <pre>
       * 时间格式 HHmmss
       * </pre>
       */
      public Builder setTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string time = 2;</code>
       *
       * <pre>
       * 时间格式 HHmmss
       * </pre>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        time_ = getDefaultInstance().getTime();
        onChanged();
        return this;
      }
      /**
       * <code>required string time = 2;</code>
       *
       * <pre>
       * 时间格式 HHmmss
       * </pre>
       */
      public Builder setTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        time_ = value;
        onChanged();
        return this;
      }

      private com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic stockBasic_ = com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic, com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.Builder, com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasicOrBuilder> stockBasicBuilder_;
      /**
       * <code>required .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
       *
       * <pre>
       * 股票信息
       * </pre>
       */
      public boolean hasStockBasic() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
       *
       * <pre>
       * 股票信息
       * </pre>
       */
      public com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic getStockBasic() {
        if (stockBasicBuilder_ == null) {
          return stockBasic_;
        } else {
          return stockBasicBuilder_.getMessage();
        }
      }
      /**
       * <code>required .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
       *
       * <pre>
       * 股票信息
       * </pre>
       */
      public Builder setStockBasic(com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic value) {
        if (stockBasicBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          stockBasic_ = value;
          onChanged();
        } else {
          stockBasicBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
       *
       * <pre>
       * 股票信息
       * </pre>
       */
      public Builder setStockBasic(
          com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.Builder builderForValue) {
        if (stockBasicBuilder_ == null) {
          stockBasic_ = builderForValue.build();
          onChanged();
        } else {
          stockBasicBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
       *
       * <pre>
       * 股票信息
       * </pre>
       */
      public Builder mergeStockBasic(com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic value) {
        if (stockBasicBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              stockBasic_ != com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.getDefaultInstance()) {
            stockBasic_ =
              com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.newBuilder(stockBasic_).mergeFrom(value).buildPartial();
          } else {
            stockBasic_ = value;
          }
          onChanged();
        } else {
          stockBasicBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
       *
       * <pre>
       * 股票信息
       * </pre>
       */
      public Builder clearStockBasic() {
        if (stockBasicBuilder_ == null) {
          stockBasic_ = com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.getDefaultInstance();
          onChanged();
        } else {
          stockBasicBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>required .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
       *
       * <pre>
       * 股票信息
       * </pre>
       */
      public com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.Builder getStockBasicBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getStockBasicFieldBuilder().getBuilder();
      }
      /**
       * <code>required .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
       *
       * <pre>
       * 股票信息
       * </pre>
       */
      public com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasicOrBuilder getStockBasicOrBuilder() {
        if (stockBasicBuilder_ != null) {
          return stockBasicBuilder_.getMessageOrBuilder();
        } else {
          return stockBasic_;
        }
      }
      /**
       * <code>required .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
       *
       * <pre>
       * 股票信息
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic, com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.Builder, com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasicOrBuilder> 
          getStockBasicFieldBuilder() {
        if (stockBasicBuilder_ == null) {
          stockBasicBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic, com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.Builder, com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasicOrBuilder>(
                  getStockBasic(),
                  getParentForChildren(),
                  isClean());
          stockBasic_ = null;
        }
        return stockBasicBuilder_;
      }

      private float close_ ;
      /**
       * <code>optional float close = 4;</code>
       *
       * <pre>
       * 今收盘价
       * </pre>
       */
      public boolean hasClose() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional float close = 4;</code>
       *
       * <pre>
       * 今收盘价
       * </pre>
       */
      public float getClose() {
        return close_;
      }
      /**
       * <code>optional float close = 4;</code>
       *
       * <pre>
       * 今收盘价
       * </pre>
       */
      public Builder setClose(float value) {
        bitField0_ |= 0x00000008;
        close_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float close = 4;</code>
       *
       * <pre>
       * 今收盘价
       * </pre>
       */
      public Builder clearClose() {
        bitField0_ = (bitField0_ & ~0x00000008);
        close_ = 0F;
        onChanged();
        return this;
      }

      private long volume_ ;
      /**
       * <code>optional int64 volume = 5;</code>
       *
       * <pre>
       * 成交总量 (股)
       * </pre>
       */
      public boolean hasVolume() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int64 volume = 5;</code>
       *
       * <pre>
       * 成交总量 (股)
       * </pre>
       */
      public long getVolume() {
        return volume_;
      }
      /**
       * <code>optional int64 volume = 5;</code>
       *
       * <pre>
       * 成交总量 (股)
       * </pre>
       */
      public Builder setVolume(long value) {
        bitField0_ |= 0x00000010;
        volume_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 volume = 5;</code>
       *
       * <pre>
       * 成交总量 (股)
       * </pre>
       */
      public Builder clearVolume() {
        bitField0_ = (bitField0_ & ~0x00000010);
        volume_ = 0L;
        onChanged();
        return this;
      }

      private double amount_ ;
      /**
       * <code>optional double amount = 6;</code>
       *
       * <pre>
       * 成交金额 (元)
       * </pre>
       */
      public boolean hasAmount() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional double amount = 6;</code>
       *
       * <pre>
       * 成交金额 (元)
       * </pre>
       */
      public double getAmount() {
        return amount_;
      }
      /**
       * <code>optional double amount = 6;</code>
       *
       * <pre>
       * 成交金额 (元)
       * </pre>
       */
      public Builder setAmount(double value) {
        bitField0_ |= 0x00000020;
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double amount = 6;</code>
       *
       * <pre>
       * 成交金额 (元)
       * </pre>
       */
      public Builder clearAmount() {
        bitField0_ = (bitField0_ & ~0x00000020);
        amount_ = 0D;
        onChanged();
        return this;
      }

      private float netChange_ ;
      /**
       * <code>optional float netChange = 7;</code>
       *
       * <pre>
       * 涨跌额
       * </pre>
       */
      public boolean hasNetChange() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional float netChange = 7;</code>
       *
       * <pre>
       * 涨跌额
       * </pre>
       */
      public float getNetChange() {
        return netChange_;
      }
      /**
       * <code>optional float netChange = 7;</code>
       *
       * <pre>
       * 涨跌额
       * </pre>
       */
      public Builder setNetChange(float value) {
        bitField0_ |= 0x00000040;
        netChange_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float netChange = 7;</code>
       *
       * <pre>
       * 涨跌额
       * </pre>
       */
      public Builder clearNetChange() {
        bitField0_ = (bitField0_ & ~0x00000040);
        netChange_ = 0F;
        onChanged();
        return this;
      }

      private float netChangeRatio_ ;
      /**
       * <code>optional float netChangeRatio = 8;</code>
       *
       * <pre>
       * 涨跌幅
       * </pre>
       */
      public boolean hasNetChangeRatio() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional float netChangeRatio = 8;</code>
       *
       * <pre>
       * 涨跌幅
       * </pre>
       */
      public float getNetChangeRatio() {
        return netChangeRatio_;
      }
      /**
       * <code>optional float netChangeRatio = 8;</code>
       *
       * <pre>
       * 涨跌幅
       * </pre>
       */
      public Builder setNetChangeRatio(float value) {
        bitField0_ |= 0x00000080;
        netChangeRatio_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float netChangeRatio = 8;</code>
       *
       * <pre>
       * 涨跌幅
       * </pre>
       */
      public Builder clearNetChangeRatio() {
        bitField0_ = (bitField0_ & ~0x00000080);
        netChangeRatio_ = 0F;
        onChanged();
        return this;
      }

      private float amplitudeRatio_ ;
      /**
       * <code>optional float amplitudeRatio = 9;</code>
       *
       * <pre>
       * 振幅
       * </pre>
       */
      public boolean hasAmplitudeRatio() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional float amplitudeRatio = 9;</code>
       *
       * <pre>
       * 振幅
       * </pre>
       */
      public float getAmplitudeRatio() {
        return amplitudeRatio_;
      }
      /**
       * <code>optional float amplitudeRatio = 9;</code>
       *
       * <pre>
       * 振幅
       * </pre>
       */
      public Builder setAmplitudeRatio(float value) {
        bitField0_ |= 0x00000100;
        amplitudeRatio_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float amplitudeRatio = 9;</code>
       *
       * <pre>
       * 振幅
       * </pre>
       */
      public Builder clearAmplitudeRatio() {
        bitField0_ = (bitField0_ & ~0x00000100);
        amplitudeRatio_ = 0F;
        onChanged();
        return this;
      }

      private float turnoverRatio_ ;
      /**
       * <code>optional float turnoverRatio = 10;</code>
       *
       * <pre>
       * 换手率
       * </pre>
       */
      public boolean hasTurnoverRatio() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional float turnoverRatio = 10;</code>
       *
       * <pre>
       * 换手率
       * </pre>
       */
      public float getTurnoverRatio() {
        return turnoverRatio_;
      }
      /**
       * <code>optional float turnoverRatio = 10;</code>
       *
       * <pre>
       * 换手率
       * </pre>
       */
      public Builder setTurnoverRatio(float value) {
        bitField0_ |= 0x00000200;
        turnoverRatio_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float turnoverRatio = 10;</code>
       *
       * <pre>
       * 换手率
       * </pre>
       */
      public Builder clearTurnoverRatio() {
        bitField0_ = (bitField0_ & ~0x00000200);
        turnoverRatio_ = 0F;
        onChanged();
        return this;
      }

      private double currencyValue_ ;
      /**
       * <code>optional double currencyValue = 11;</code>
       *
       * <pre>
       * 流通市值
       * </pre>
       */
      public boolean hasCurrencyValue() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional double currencyValue = 11;</code>
       *
       * <pre>
       * 流通市值
       * </pre>
       */
      public double getCurrencyValue() {
        return currencyValue_;
      }
      /**
       * <code>optional double currencyValue = 11;</code>
       *
       * <pre>
       * 流通市值
       * </pre>
       */
      public Builder setCurrencyValue(double value) {
        bitField0_ |= 0x00000400;
        currencyValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double currencyValue = 11;</code>
       *
       * <pre>
       * 流通市值
       * </pre>
       */
      public Builder clearCurrencyValue() {
        bitField0_ = (bitField0_ & ~0x00000400);
        currencyValue_ = 0D;
        onChanged();
        return this;
      }

      private double capitalization_ ;
      /**
       * <code>optional double capitalization = 12;</code>
       *
       * <pre>
       * 总市值
       * </pre>
       */
      public boolean hasCapitalization() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional double capitalization = 12;</code>
       *
       * <pre>
       * 总市值
       * </pre>
       */
      public double getCapitalization() {
        return capitalization_;
      }
      /**
       * <code>optional double capitalization = 12;</code>
       *
       * <pre>
       * 总市值
       * </pre>
       */
      public Builder setCapitalization(double value) {
        bitField0_ |= 0x00000800;
        capitalization_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double capitalization = 12;</code>
       *
       * <pre>
       * 总市值
       * </pre>
       */
      public Builder clearCapitalization() {
        bitField0_ = (bitField0_ & ~0x00000800);
        capitalization_ = 0D;
        onChanged();
        return this;
      }

      private float lyrPeratio_ ;
      /**
       * <code>optional float lyrPeratio = 13;</code>
       *
       * <pre>
       * LYR市盈率
       * </pre>
       */
      public boolean hasLyrPeratio() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional float lyrPeratio = 13;</code>
       *
       * <pre>
       * LYR市盈率
       * </pre>
       */
      public float getLyrPeratio() {
        return lyrPeratio_;
      }
      /**
       * <code>optional float lyrPeratio = 13;</code>
       *
       * <pre>
       * LYR市盈率
       * </pre>
       */
      public Builder setLyrPeratio(float value) {
        bitField0_ |= 0x00001000;
        lyrPeratio_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float lyrPeratio = 13;</code>
       *
       * <pre>
       * LYR市盈率
       * </pre>
       */
      public Builder clearLyrPeratio() {
        bitField0_ = (bitField0_ & ~0x00001000);
        lyrPeratio_ = 0F;
        onChanged();
        return this;
      }

      private float mrqPeratio_ ;
      /**
       * <code>optional float mrqPeratio = 14;</code>
       *
       * <pre>
       * mrq市盈率
       * </pre>
       */
      public boolean hasMrqPeratio() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>optional float mrqPeratio = 14;</code>
       *
       * <pre>
       * mrq市盈率
       * </pre>
       */
      public float getMrqPeratio() {
        return mrqPeratio_;
      }
      /**
       * <code>optional float mrqPeratio = 14;</code>
       *
       * <pre>
       * mrq市盈率
       * </pre>
       */
      public Builder setMrqPeratio(float value) {
        bitField0_ |= 0x00002000;
        mrqPeratio_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float mrqPeratio = 14;</code>
       *
       * <pre>
       * mrq市盈率
       * </pre>
       */
      public Builder clearMrqPeratio() {
        bitField0_ = (bitField0_ & ~0x00002000);
        mrqPeratio_ = 0F;
        onChanged();
        return this;
      }

      private float ttmPeratio_ ;
      /**
       * <code>optional float ttmPeratio = 15;</code>
       *
       * <pre>
       * TTM市盈率
       * </pre>
       */
      public boolean hasTtmPeratio() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>optional float ttmPeratio = 15;</code>
       *
       * <pre>
       * TTM市盈率
       * </pre>
       */
      public float getTtmPeratio() {
        return ttmPeratio_;
      }
      /**
       * <code>optional float ttmPeratio = 15;</code>
       *
       * <pre>
       * TTM市盈率
       * </pre>
       */
      public Builder setTtmPeratio(float value) {
        bitField0_ |= 0x00004000;
        ttmPeratio_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float ttmPeratio = 15;</code>
       *
       * <pre>
       * TTM市盈率
       * </pre>
       */
      public Builder clearTtmPeratio() {
        bitField0_ = (bitField0_ & ~0x00004000);
        ttmPeratio_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.baidu.stock.quote.protocbuf.BriefSnapShot)
    }

    static {
      defaultInstance = new BriefSnapShot(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.baidu.stock.quote.protocbuf.BriefSnapShot)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_baidu_stock_quote_protocbuf_BriefSnapShot_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_baidu_stock_quote_protocbuf_BriefSnapShot_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023BriefSnapShot.proto\022\037com.baidu.stock.q" +
      "uote.protocbuf\032\020StockBasic.proto\"\340\002\n\rBri" +
      "efSnapShot\022\014\n\004date\030\001 \002(\t\022\014\n\004time\030\002 \002(\t\022?" +
      "\n\nstockBasic\030\003 \002(\0132+.com.baidu.stock.quo" +
      "te.protocbuf.StockBasic\022\r\n\005close\030\004 \001(\002\022\016" +
      "\n\006volume\030\005 \001(\003\022\016\n\006amount\030\006 \001(\001\022\021\n\tnetCha" +
      "nge\030\007 \001(\002\022\026\n\016netChangeRatio\030\010 \001(\002\022\026\n\016amp" +
      "litudeRatio\030\t \001(\002\022\025\n\rturnoverRatio\030\n \001(\002" +
      "\022\025\n\rcurrencyValue\030\013 \001(\001\022\026\n\016capitalizatio" +
      "n\030\014 \001(\001\022\022\n\nlyrPeratio\030\r \001(\002\022\022\n\nmrqPerati",
      "o\030\016 \001(\002\022\022\n\nttmPeratio\030\017 \001(\002B5\n\037com.baidu" +
      ".stock.quote.protocbufB\022BriefSnapShotPro" +
      "to"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.baidu.stock.quote.protocbuf.StockBasicProto.getDescriptor(),
        }, assigner);
    internal_static_com_baidu_stock_quote_protocbuf_BriefSnapShot_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_baidu_stock_quote_protocbuf_BriefSnapShot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_baidu_stock_quote_protocbuf_BriefSnapShot_descriptor,
        new java.lang.String[] { "Date", "Time", "StockBasic", "Close", "Volume", "Amount", "NetChange", "NetChangeRatio", "AmplitudeRatio", "TurnoverRatio", "CurrencyValue", "Capitalization", "LyrPeratio", "MrqPeratio", "TtmPeratio", });
    com.baidu.stock.quote.protocbuf.StockBasicProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
