// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CodeList.proto

package com.baidu.stock.quote.protocbuf;

public final class CodeListProto {
	private CodeListProto() {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistry registry) {
	}

	public interface CodeListOrBuilder extends
	// @@protoc_insertion_point(interface_extends:com.baidu.stock.quote.protocbuf.CodeList)
			com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>required string date = 1;</code>
		 *
		 * <pre>
		 * 日期
		 * </pre>
		 */
		boolean hasDate();

		/**
		 * <code>required string date = 1;</code>
		 *
		 * <pre>
		 * 日期
		 * </pre>
		 */
		java.lang.String getDate();

		/**
		 * <code>required string date = 1;</code>
		 *
		 * <pre>
		 * 日期
		 * </pre>
		 */
		com.google.protobuf.ByteString getDateBytes();

		/**
		 * <code>required string exchange = 2;</code>
		 *
		 * <pre>
		 * 交易所
		 * </pre>
		 */
		boolean hasExchange();

		/**
		 * <code>required string exchange = 2;</code>
		 *
		 * <pre>
		 * 交易所
		 * </pre>
		 */
		java.lang.String getExchange();

		/**
		 * <code>required string exchange = 2;</code>
		 *
		 * <pre>
		 * 交易所
		 * </pre>
		 */
		com.google.protobuf.ByteString getExchangeBytes();

		/**
		 * <code>repeated .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
		 *
		 * <pre>
		 * 证券
		 * </pre>
		 */
		java.util.List<com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic> getStockBasicList();

		/**
		 * <code>repeated .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
		 *
		 * <pre>
		 * 证券
		 * </pre>
		 */
		com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic getStockBasic(
				int index);

		/**
		 * <code>repeated .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
		 *
		 * <pre>
		 * 证券
		 * </pre>
		 */
		int getStockBasicCount();

		/**
		 * <code>repeated .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
		 *
		 * <pre>
		 * 证券
		 * </pre>
		 */
		java.util.List<? extends com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasicOrBuilder> getStockBasicOrBuilderList();

		/**
		 * <code>repeated .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
		 *
		 * <pre>
		 * 证券
		 * </pre>
		 */
		com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasicOrBuilder getStockBasicOrBuilder(
				int index);
	}

	/**
	 * Protobuf type {@code com.baidu.stock.quote.protocbuf.CodeList}
	 */
	public static final class CodeList extends
			com.google.protobuf.GeneratedMessage implements
	// @@protoc_insertion_point(message_implements:com.baidu.stock.quote.protocbuf.CodeList)
			CodeListOrBuilder {
		// Use CodeList.newBuilder() to construct.
		private CodeList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
			super(builder);
			this.unknownFields = builder.getUnknownFields();
		}

		private CodeList(boolean noInit) {
			this.unknownFields = com.google.protobuf.UnknownFieldSet
					.getDefaultInstance();
		}

		private static final CodeList defaultInstance;

		public static CodeList getDefaultInstance() {
			return defaultInstance;
		}

		public CodeList getDefaultInstanceForType() {
			return defaultInstance;
		}

		private final com.google.protobuf.UnknownFieldSet unknownFields;

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return this.unknownFields;
		}

		private CodeList(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			initFields();
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
					.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							done = true;
						}
						break;
					}
					case 10: {
						com.google.protobuf.ByteString bs = input.readBytes();
						bitField0_ |= 0x00000001;
						date_ = bs;
						break;
					}
					case 18: {
						com.google.protobuf.ByteString bs = input.readBytes();
						bitField0_ |= 0x00000002;
						exchange_ = bs;
						break;
					}
					case 26: {
						if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
							stockBasic_ = new java.util.ArrayList<com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic>();
							mutable_bitField0_ |= 0x00000004;
						}
						stockBasic_
								.add(input
										.readMessage(
												com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.PARSER,
												extensionRegistry));
						break;
					}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(
						e.getMessage()).setUnfinishedMessage(this);
			} finally {
				if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
					stockBasic_ = java.util.Collections
							.unmodifiableList(stockBasic_);
				}
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return com.baidu.stock.quote.protocbuf.CodeListProto.internal_static_com_baidu_stock_quote_protocbuf_CodeList_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return com.baidu.stock.quote.protocbuf.CodeListProto.internal_static_com_baidu_stock_quote_protocbuf_CodeList_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
							com.baidu.stock.quote.protocbuf.CodeListProto.CodeList.class,
							com.baidu.stock.quote.protocbuf.CodeListProto.CodeList.Builder.class);
		}

		public static com.google.protobuf.Parser<CodeList> PARSER = new com.google.protobuf.AbstractParser<CodeList>() {
			public CodeList parsePartialFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new CodeList(input, extensionRegistry);
			}
		};

		@java.lang.Override
		public com.google.protobuf.Parser<CodeList> getParserForType() {
			return PARSER;
		}

		private int bitField0_;
		public static final int DATE_FIELD_NUMBER = 1;
		private java.lang.Object date_;

		/**
		 * <code>required string date = 1;</code>
		 *
		 * <pre>
		 * 日期
		 * </pre>
		 */
		public boolean hasDate() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		/**
		 * <code>required string date = 1;</code>
		 *
		 * <pre>
		 * 日期
		 * </pre>
		 */
		public java.lang.String getDate() {
			java.lang.Object ref = date_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					date_ = s;
				}
				return s;
			}
		}

		/**
		 * <code>required string date = 1;</code>
		 *
		 * <pre>
		 * 日期
		 * </pre>
		 */
		public com.google.protobuf.ByteString getDateBytes() {
			java.lang.Object ref = date_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((java.lang.String) ref);
				date_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int EXCHANGE_FIELD_NUMBER = 2;
		private java.lang.Object exchange_;

		/**
		 * <code>required string exchange = 2;</code>
		 *
		 * <pre>
		 * 交易所
		 * </pre>
		 */
		public boolean hasExchange() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		/**
		 * <code>required string exchange = 2;</code>
		 *
		 * <pre>
		 * 交易所
		 * </pre>
		 */
		public java.lang.String getExchange() {
			java.lang.Object ref = exchange_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					exchange_ = s;
				}
				return s;
			}
		}

		/**
		 * <code>required string exchange = 2;</code>
		 *
		 * <pre>
		 * 交易所
		 * </pre>
		 */
		public com.google.protobuf.ByteString getExchangeBytes() {
			java.lang.Object ref = exchange_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((java.lang.String) ref);
				exchange_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int STOCKBASIC_FIELD_NUMBER = 3;
		private java.util.List<com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic> stockBasic_;

		/**
		 * <code>repeated .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
		 *
		 * <pre>
		 * 证券
		 * </pre>
		 */
		public java.util.List<com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic> getStockBasicList() {
			return stockBasic_;
		}

		/**
		 * <code>repeated .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
		 *
		 * <pre>
		 * 证券
		 * </pre>
		 */
		public java.util.List<? extends com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasicOrBuilder> getStockBasicOrBuilderList() {
			return stockBasic_;
		}

		/**
		 * <code>repeated .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
		 *
		 * <pre>
		 * 证券
		 * </pre>
		 */
		public int getStockBasicCount() {
			return stockBasic_.size();
		}

		/**
		 * <code>repeated .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
		 *
		 * <pre>
		 * 证券
		 * </pre>
		 */
		public com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic getStockBasic(
				int index) {
			return stockBasic_.get(index);
		}

		/**
		 * <code>repeated .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
		 *
		 * <pre>
		 * 证券
		 * </pre>
		 */
		public com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasicOrBuilder getStockBasicOrBuilder(
				int index) {
			return stockBasic_.get(index);
		}

		private void initFields() {
			date_ = "";
			exchange_ = "";
			stockBasic_ = java.util.Collections.emptyList();
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1)
				return true;
			if (isInitialized == 0)
				return false;

			if (!hasDate()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasExchange()) {
				memoizedIsInitialized = 0;
				return false;
			}
			for (int i = 0; i < getStockBasicCount(); i++) {
				if (!getStockBasic(i).isInitialized()) {
					memoizedIsInitialized = 0;
					return false;
				}
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeBytes(1, getDateBytes());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeBytes(2, getExchangeBytes());
			}
			for (int i = 0; i < stockBasic_.size(); i++) {
				output.writeMessage(3, stockBasic_.get(i));
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						1, getDateBytes());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						2, getExchangeBytes());
			}
			for (int i = 0; i < stockBasic_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream
						.computeMessageSize(3, stockBasic_.get(i));
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static com.baidu.stock.quote.protocbuf.CodeListProto.CodeList parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static com.baidu.stock.quote.protocbuf.CodeListProto.CodeList parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static com.baidu.stock.quote.protocbuf.CodeListProto.CodeList parseFrom(
				byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static com.baidu.stock.quote.protocbuf.CodeListProto.CodeList parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static com.baidu.stock.quote.protocbuf.CodeListProto.CodeList parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static com.baidu.stock.quote.protocbuf.CodeListProto.CodeList parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static com.baidu.stock.quote.protocbuf.CodeListProto.CodeList parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input);
		}

		public static com.baidu.stock.quote.protocbuf.CodeListProto.CodeList parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input, extensionRegistry);
		}

		public static com.baidu.stock.quote.protocbuf.CodeListProto.CodeList parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static com.baidu.stock.quote.protocbuf.CodeListProto.CodeList parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(
				com.baidu.stock.quote.protocbuf.CodeListProto.CodeList prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code com.baidu.stock.quote.protocbuf.CodeList}
		 */
		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder> implements
		// @@protoc_insertion_point(builder_implements:com.baidu.stock.quote.protocbuf.CodeList)
				com.baidu.stock.quote.protocbuf.CodeListProto.CodeListOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return com.baidu.stock.quote.protocbuf.CodeListProto.internal_static_com_baidu_stock_quote_protocbuf_CodeList_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return com.baidu.stock.quote.protocbuf.CodeListProto.internal_static_com_baidu_stock_quote_protocbuf_CodeList_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								com.baidu.stock.quote.protocbuf.CodeListProto.CodeList.class,
								com.baidu.stock.quote.protocbuf.CodeListProto.CodeList.Builder.class);
			}

			// Construct using
			// com.baidu.stock.quote.protocbuf.CodeListProto.CodeList.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(
					com.google.protobuf.GeneratedMessage.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
					getStockBasicFieldBuilder();
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				date_ = "";
				bitField0_ = (bitField0_ & ~0x00000001);
				exchange_ = "";
				bitField0_ = (bitField0_ & ~0x00000002);
				if (stockBasicBuilder_ == null) {
					stockBasic_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000004);
				} else {
					stockBasicBuilder_.clear();
				}
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return com.baidu.stock.quote.protocbuf.CodeListProto.internal_static_com_baidu_stock_quote_protocbuf_CodeList_descriptor;
			}

			public com.baidu.stock.quote.protocbuf.CodeListProto.CodeList getDefaultInstanceForType() {
				return com.baidu.stock.quote.protocbuf.CodeListProto.CodeList
						.getDefaultInstance();
			}

			public com.baidu.stock.quote.protocbuf.CodeListProto.CodeList build() {
				com.baidu.stock.quote.protocbuf.CodeListProto.CodeList result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			public com.baidu.stock.quote.protocbuf.CodeListProto.CodeList buildPartial() {
				com.baidu.stock.quote.protocbuf.CodeListProto.CodeList result = new com.baidu.stock.quote.protocbuf.CodeListProto.CodeList(
						this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.date_ = date_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.exchange_ = exchange_;
				if (stockBasicBuilder_ == null) {
					if (((bitField0_ & 0x00000004) == 0x00000004)) {
						stockBasic_ = java.util.Collections
								.unmodifiableList(stockBasic_);
						bitField0_ = (bitField0_ & ~0x00000004);
					}
					result.stockBasic_ = stockBasic_;
				} else {
					result.stockBasic_ = stockBasicBuilder_.build();
				}
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof com.baidu.stock.quote.protocbuf.CodeListProto.CodeList) {
					return mergeFrom((com.baidu.stock.quote.protocbuf.CodeListProto.CodeList) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(
					com.baidu.stock.quote.protocbuf.CodeListProto.CodeList other) {
				if (other == com.baidu.stock.quote.protocbuf.CodeListProto.CodeList
						.getDefaultInstance())
					return this;
				if (other.hasDate()) {
					bitField0_ |= 0x00000001;
					date_ = other.date_;
					onChanged();
				}
				if (other.hasExchange()) {
					bitField0_ |= 0x00000002;
					exchange_ = other.exchange_;
					onChanged();
				}
				if (stockBasicBuilder_ == null) {
					if (!other.stockBasic_.isEmpty()) {
						if (stockBasic_.isEmpty()) {
							stockBasic_ = other.stockBasic_;
							bitField0_ = (bitField0_ & ~0x00000004);
						} else {
							ensureStockBasicIsMutable();
							stockBasic_.addAll(other.stockBasic_);
						}
						onChanged();
					}
				} else {
					if (!other.stockBasic_.isEmpty()) {
						if (stockBasicBuilder_.isEmpty()) {
							stockBasicBuilder_.dispose();
							stockBasicBuilder_ = null;
							stockBasic_ = other.stockBasic_;
							bitField0_ = (bitField0_ & ~0x00000004);
							stockBasicBuilder_ = com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ? getStockBasicFieldBuilder()
									: null;
						} else {
							stockBasicBuilder_
									.addAllMessages(other.stockBasic_);
						}
					}
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				if (!hasDate()) {

					return false;
				}
				if (!hasExchange()) {

					return false;
				}
				for (int i = 0; i < getStockBasicCount(); i++) {
					if (!getStockBasic(i).isInitialized()) {

						return false;
					}
				}
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.baidu.stock.quote.protocbuf.CodeListProto.CodeList parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input,
							extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (com.baidu.stock.quote.protocbuf.CodeListProto.CodeList) e
							.getUnfinishedMessage();
					throw e;
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int bitField0_;

			private java.lang.Object date_ = "";

			/**
			 * <code>required string date = 1;</code>
			 *
			 * <pre>
			 * 日期
			 * </pre>
			 */
			public boolean hasDate() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			/**
			 * <code>required string date = 1;</code>
			 *
			 * <pre>
			 * 日期
			 * </pre>
			 */
			public java.lang.String getDate() {
				java.lang.Object ref = date_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					if (bs.isValidUtf8()) {
						date_ = s;
					}
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>required string date = 1;</code>
			 *
			 * <pre>
			 * 日期
			 * </pre>
			 */
			public com.google.protobuf.ByteString getDateBytes() {
				java.lang.Object ref = date_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					date_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>required string date = 1;</code>
			 *
			 * <pre>
			 * 日期
			 * </pre>
			 */
			public Builder setDate(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				date_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required string date = 1;</code>
			 *
			 * <pre>
			 * 日期
			 * </pre>
			 */
			public Builder clearDate() {
				bitField0_ = (bitField0_ & ~0x00000001);
				date_ = getDefaultInstance().getDate();
				onChanged();
				return this;
			}

			/**
			 * <code>required string date = 1;</code>
			 *
			 * <pre>
			 * 日期
			 * </pre>
			 */
			public Builder setDateBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				date_ = value;
				onChanged();
				return this;
			}

			private java.lang.Object exchange_ = "";

			/**
			 * <code>required string exchange = 2;</code>
			 *
			 * <pre>
			 * 交易所
			 * </pre>
			 */
			public boolean hasExchange() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			/**
			 * <code>required string exchange = 2;</code>
			 *
			 * <pre>
			 * 交易所
			 * </pre>
			 */
			public java.lang.String getExchange() {
				java.lang.Object ref = exchange_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					if (bs.isValidUtf8()) {
						exchange_ = s;
					}
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>required string exchange = 2;</code>
			 *
			 * <pre>
			 * 交易所
			 * </pre>
			 */
			public com.google.protobuf.ByteString getExchangeBytes() {
				java.lang.Object ref = exchange_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					exchange_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>required string exchange = 2;</code>
			 *
			 * <pre>
			 * 交易所
			 * </pre>
			 */
			public Builder setExchange(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000002;
				exchange_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required string exchange = 2;</code>
			 *
			 * <pre>
			 * 交易所
			 * </pre>
			 */
			public Builder clearExchange() {
				bitField0_ = (bitField0_ & ~0x00000002);
				exchange_ = getDefaultInstance().getExchange();
				onChanged();
				return this;
			}

			/**
			 * <code>required string exchange = 2;</code>
			 *
			 * <pre>
			 * 交易所
			 * </pre>
			 */
			public Builder setExchangeBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000002;
				exchange_ = value;
				onChanged();
				return this;
			}

			private java.util.List<com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic> stockBasic_ = java.util.Collections
					.emptyList();

			private void ensureStockBasicIsMutable() {
				if (!((bitField0_ & 0x00000004) == 0x00000004)) {
					stockBasic_ = new java.util.ArrayList<com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic>(
							stockBasic_);
					bitField0_ |= 0x00000004;
				}
			}

			private com.google.protobuf.RepeatedFieldBuilder<com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic, com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.Builder, com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasicOrBuilder> stockBasicBuilder_;

			/**
			 * <code>repeated .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
			 *
			 * <pre>
			 * 证券
			 * </pre>
			 */
			public java.util.List<com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic> getStockBasicList() {
				if (stockBasicBuilder_ == null) {
					return java.util.Collections.unmodifiableList(stockBasic_);
				} else {
					return stockBasicBuilder_.getMessageList();
				}
			}

			/**
			 * <code>repeated .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
			 *
			 * <pre>
			 * 证券
			 * </pre>
			 */
			public int getStockBasicCount() {
				if (stockBasicBuilder_ == null) {
					return stockBasic_.size();
				} else {
					return stockBasicBuilder_.getCount();
				}
			}

			/**
			 * <code>repeated .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
			 *
			 * <pre>
			 * 证券
			 * </pre>
			 */
			public com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic getStockBasic(
					int index) {
				if (stockBasicBuilder_ == null) {
					return stockBasic_.get(index);
				} else {
					return stockBasicBuilder_.getMessage(index);
				}
			}

			/**
			 * <code>repeated .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
			 *
			 * <pre>
			 * 证券
			 * </pre>
			 */
			public Builder setStockBasic(
					int index,
					com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic value) {
				if (stockBasicBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureStockBasicIsMutable();
					stockBasic_.set(index, value);
					onChanged();
				} else {
					stockBasicBuilder_.setMessage(index, value);
				}
				return this;
			}

			/**
			 * <code>repeated .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
			 *
			 * <pre>
			 * 证券
			 * </pre>
			 */
			public Builder setStockBasic(
					int index,
					com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.Builder builderForValue) {
				if (stockBasicBuilder_ == null) {
					ensureStockBasicIsMutable();
					stockBasic_.set(index, builderForValue.build());
					onChanged();
				} else {
					stockBasicBuilder_.setMessage(index,
							builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
			 *
			 * <pre>
			 * 证券
			 * </pre>
			 */
			public Builder addStockBasic(
					com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic value) {
				if (stockBasicBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureStockBasicIsMutable();
					stockBasic_.add(value);
					onChanged();
				} else {
					stockBasicBuilder_.addMessage(value);
				}
				return this;
			}

			/**
			 * <code>repeated .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
			 *
			 * <pre>
			 * 证券
			 * </pre>
			 */
			public Builder addStockBasic(
					int index,
					com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic value) {
				if (stockBasicBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureStockBasicIsMutable();
					stockBasic_.add(index, value);
					onChanged();
				} else {
					stockBasicBuilder_.addMessage(index, value);
				}
				return this;
			}

			/**
			 * <code>repeated .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
			 *
			 * <pre>
			 * 证券
			 * </pre>
			 */
			public Builder addStockBasic(
					com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.Builder builderForValue) {
				if (stockBasicBuilder_ == null) {
					ensureStockBasicIsMutable();
					stockBasic_.add(builderForValue.build());
					onChanged();
				} else {
					stockBasicBuilder_.addMessage(builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
			 *
			 * <pre>
			 * 证券
			 * </pre>
			 */
			public Builder addStockBasic(
					int index,
					com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.Builder builderForValue) {
				if (stockBasicBuilder_ == null) {
					ensureStockBasicIsMutable();
					stockBasic_.add(index, builderForValue.build());
					onChanged();
				} else {
					stockBasicBuilder_.addMessage(index,
							builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
			 *
			 * <pre>
			 * 证券
			 * </pre>
			 */
			public Builder addAllStockBasic(
					java.lang.Iterable<? extends com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic> values) {
				if (stockBasicBuilder_ == null) {
					ensureStockBasicIsMutable();
					com.google.protobuf.AbstractMessageLite.Builder.addAll(
							values, stockBasic_);
					onChanged();
				} else {
					stockBasicBuilder_.addAllMessages(values);
				}
				return this;
			}

			/**
			 * <code>repeated .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
			 *
			 * <pre>
			 * 证券
			 * </pre>
			 */
			public Builder clearStockBasic() {
				if (stockBasicBuilder_ == null) {
					stockBasic_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000004);
					onChanged();
				} else {
					stockBasicBuilder_.clear();
				}
				return this;
			}

			/**
			 * <code>repeated .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
			 *
			 * <pre>
			 * 证券
			 * </pre>
			 */
			public Builder removeStockBasic(int index) {
				if (stockBasicBuilder_ == null) {
					ensureStockBasicIsMutable();
					stockBasic_.remove(index);
					onChanged();
				} else {
					stockBasicBuilder_.remove(index);
				}
				return this;
			}

			/**
			 * <code>repeated .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
			 *
			 * <pre>
			 * 证券
			 * </pre>
			 */
			public com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.Builder getStockBasicBuilder(
					int index) {
				return getStockBasicFieldBuilder().getBuilder(index);
			}

			/**
			 * <code>repeated .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
			 *
			 * <pre>
			 * 证券
			 * </pre>
			 */
			public com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasicOrBuilder getStockBasicOrBuilder(
					int index) {
				if (stockBasicBuilder_ == null) {
					return stockBasic_.get(index);
				} else {
					return stockBasicBuilder_.getMessageOrBuilder(index);
				}
			}

			/**
			 * <code>repeated .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
			 *
			 * <pre>
			 * 证券
			 * </pre>
			 */
			public java.util.List<? extends com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasicOrBuilder> getStockBasicOrBuilderList() {
				if (stockBasicBuilder_ != null) {
					return stockBasicBuilder_.getMessageOrBuilderList();
				} else {
					return java.util.Collections.unmodifiableList(stockBasic_);
				}
			}

			/**
			 * <code>repeated .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
			 *
			 * <pre>
			 * 证券
			 * </pre>
			 */
			public com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.Builder addStockBasicBuilder() {
				return getStockBasicFieldBuilder()
						.addBuilder(
								com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic
										.getDefaultInstance());
			}

			/**
			 * <code>repeated .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
			 *
			 * <pre>
			 * 证券
			 * </pre>
			 */
			public com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.Builder addStockBasicBuilder(
					int index) {
				return getStockBasicFieldBuilder()
						.addBuilder(
								index,
								com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic
										.getDefaultInstance());
			}

			/**
			 * <code>repeated .com.baidu.stock.quote.protocbuf.StockBasic stockBasic = 3;</code>
			 *
			 * <pre>
			 * 证券
			 * </pre>
			 */
			public java.util.List<com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.Builder> getStockBasicBuilderList() {
				return getStockBasicFieldBuilder().getBuilderList();
			}

			private com.google.protobuf.RepeatedFieldBuilder<com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic, com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.Builder, com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasicOrBuilder> getStockBasicFieldBuilder() {
				if (stockBasicBuilder_ == null) {
					stockBasicBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic, com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.Builder, com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasicOrBuilder>(
							stockBasic_,
							((bitField0_ & 0x00000004) == 0x00000004),
							getParentForChildren(), isClean());
					stockBasic_ = null;
				}
				return stockBasicBuilder_;
			}

			// @@protoc_insertion_point(builder_scope:com.baidu.stock.quote.protocbuf.CodeList)
		}

		static {
			defaultInstance = new CodeList(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:com.baidu.stock.quote.protocbuf.CodeList)
	}

	private static final com.google.protobuf.Descriptors.Descriptor internal_static_com_baidu_stock_quote_protocbuf_CodeList_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_com_baidu_stock_quote_protocbuf_CodeList_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = { "\n\016CodeList.proto\022\037com.baidu.stock.quote."
				+ "protocbuf\032\020StockBasic.proto\"k\n\010CodeList\022"
				+ "\014\n\004date\030\001 \002(\t\022\020\n\010exchange\030\002 \002(\t\022?\n\nstock"
				+ "Basic\030\003 \003(\0132+.com.baidu.stock.quote.prot"
				+ "ocbuf.StockBasicB0\n\037com.baidu.stock.quot"
				+ "e.protocbufB\rCodeListProto" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public com.google.protobuf.ExtensionRegistry assignDescriptors(
					com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor
				.internalBuildGeneratedFileFrom(
						descriptorData,
						new com.google.protobuf.Descriptors.FileDescriptor[] { com.baidu.stock.quote.protocbuf.StockBasicProto
								.getDescriptor(), }, assigner);
		internal_static_com_baidu_stock_quote_protocbuf_CodeList_descriptor = getDescriptor()
				.getMessageTypes().get(0);
		internal_static_com_baidu_stock_quote_protocbuf_CodeList_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
				internal_static_com_baidu_stock_quote_protocbuf_CodeList_descriptor,
				new java.lang.String[] { "Date", "Exchange", "StockBasic", });
		com.baidu.stock.quote.protocbuf.StockBasicProto.getDescriptor();
	}

	// @@protoc_insertion_point(outer_class_scope)
}
