// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RankList.proto

package com.baidu.stock.quote.protocbuf;

public final class RankListProto {
  private RankListProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RankListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.baidu.stock.quote.protocbuf.RankList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 date = 1;</code>
     *
     * <pre>
     *日期格式yyyyMMdd
     * </pre>
     */
    boolean hasDate();
    /**
     * <code>required int32 date = 1;</code>
     *
     * <pre>
     *日期格式yyyyMMdd
     * </pre>
     */
    int getDate();

    /**
     * <code>required int32 time = 2;</code>
     *
     * <pre>
     *时间格式HHmmssSSS
     * </pre>
     */
    boolean hasTime();
    /**
     * <code>required int32 time = 2;</code>
     *
     * <pre>
     *时间格式HHmmssSSS
     * </pre>
     */
    int getTime();

    /**
     * <code>repeated .com.baidu.stock.quote.protocbuf.Rank rank = 3;</code>
     *
     * <pre>
     *排行内容
     * </pre>
     */
    java.util.List<com.baidu.stock.quote.protocbuf.RankProto.Rank> 
        getRankList();
    /**
     * <code>repeated .com.baidu.stock.quote.protocbuf.Rank rank = 3;</code>
     *
     * <pre>
     *排行内容
     * </pre>
     */
    com.baidu.stock.quote.protocbuf.RankProto.Rank getRank(int index);
    /**
     * <code>repeated .com.baidu.stock.quote.protocbuf.Rank rank = 3;</code>
     *
     * <pre>
     *排行内容
     * </pre>
     */
    int getRankCount();
    /**
     * <code>repeated .com.baidu.stock.quote.protocbuf.Rank rank = 3;</code>
     *
     * <pre>
     *排行内容
     * </pre>
     */
    java.util.List<? extends com.baidu.stock.quote.protocbuf.RankProto.RankOrBuilder> 
        getRankOrBuilderList();
    /**
     * <code>repeated .com.baidu.stock.quote.protocbuf.Rank rank = 3;</code>
     *
     * <pre>
     *排行内容
     * </pre>
     */
    com.baidu.stock.quote.protocbuf.RankProto.RankOrBuilder getRankOrBuilder(
        int index);

    /**
     * <code>optional string catName = 4;</code>
     *
     * <pre>
     *分类名称
     * </pre>
     */
    boolean hasCatName();
    /**
     * <code>optional string catName = 4;</code>
     *
     * <pre>
     *分类名称
     * </pre>
     */
    java.lang.String getCatName();
    /**
     * <code>optional string catName = 4;</code>
     *
     * <pre>
     *分类名称
     * </pre>
     */
    com.google.protobuf.ByteString
        getCatNameBytes();

    /**
     * <code>optional string catDesc = 5;</code>
     *
     * <pre>
     *分类描述
     * </pre>
     */
    boolean hasCatDesc();
    /**
     * <code>optional string catDesc = 5;</code>
     *
     * <pre>
     *分类描述
     * </pre>
     */
    java.lang.String getCatDesc();
    /**
     * <code>optional string catDesc = 5;</code>
     *
     * <pre>
     *分类描述
     * </pre>
     */
    com.google.protobuf.ByteString
        getCatDescBytes();
  }
  /**
   * Protobuf type {@code com.baidu.stock.quote.protocbuf.RankList}
   */
  public static final class RankList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.baidu.stock.quote.protocbuf.RankList)
      RankListOrBuilder {
    // Use RankList.newBuilder() to construct.
    private RankList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RankList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RankList defaultInstance;
    public static RankList getDefaultInstance() {
      return defaultInstance;
    }

    public RankList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RankList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              date_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              time_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                rank_ = new java.util.ArrayList<com.baidu.stock.quote.protocbuf.RankProto.Rank>();
                mutable_bitField0_ |= 0x00000004;
              }
              rank_.add(input.readMessage(com.baidu.stock.quote.protocbuf.RankProto.Rank.PARSER, extensionRegistry));
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              catName_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              catDesc_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          rank_ = java.util.Collections.unmodifiableList(rank_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.baidu.stock.quote.protocbuf.RankListProto.internal_static_com_baidu_stock_quote_protocbuf_RankList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.baidu.stock.quote.protocbuf.RankListProto.internal_static_com_baidu_stock_quote_protocbuf_RankList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.baidu.stock.quote.protocbuf.RankListProto.RankList.class, com.baidu.stock.quote.protocbuf.RankListProto.RankList.Builder.class);
    }

    public static com.google.protobuf.Parser<RankList> PARSER =
        new com.google.protobuf.AbstractParser<RankList>() {
      public RankList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RankList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RankList> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int DATE_FIELD_NUMBER = 1;
    private int date_;
    /**
     * <code>required int32 date = 1;</code>
     *
     * <pre>
     *日期格式yyyyMMdd
     * </pre>
     */
    public boolean hasDate() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 date = 1;</code>
     *
     * <pre>
     *日期格式yyyyMMdd
     * </pre>
     */
    public int getDate() {
      return date_;
    }

    public static final int TIME_FIELD_NUMBER = 2;
    private int time_;
    /**
     * <code>required int32 time = 2;</code>
     *
     * <pre>
     *时间格式HHmmssSSS
     * </pre>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 time = 2;</code>
     *
     * <pre>
     *时间格式HHmmssSSS
     * </pre>
     */
    public int getTime() {
      return time_;
    }

    public static final int RANK_FIELD_NUMBER = 3;
    private java.util.List<com.baidu.stock.quote.protocbuf.RankProto.Rank> rank_;
    /**
     * <code>repeated .com.baidu.stock.quote.protocbuf.Rank rank = 3;</code>
     *
     * <pre>
     *排行内容
     * </pre>
     */
    public java.util.List<com.baidu.stock.quote.protocbuf.RankProto.Rank> getRankList() {
      return rank_;
    }
    /**
     * <code>repeated .com.baidu.stock.quote.protocbuf.Rank rank = 3;</code>
     *
     * <pre>
     *排行内容
     * </pre>
     */
    public java.util.List<? extends com.baidu.stock.quote.protocbuf.RankProto.RankOrBuilder> 
        getRankOrBuilderList() {
      return rank_;
    }
    /**
     * <code>repeated .com.baidu.stock.quote.protocbuf.Rank rank = 3;</code>
     *
     * <pre>
     *排行内容
     * </pre>
     */
    public int getRankCount() {
      return rank_.size();
    }
    /**
     * <code>repeated .com.baidu.stock.quote.protocbuf.Rank rank = 3;</code>
     *
     * <pre>
     *排行内容
     * </pre>
     */
    public com.baidu.stock.quote.protocbuf.RankProto.Rank getRank(int index) {
      return rank_.get(index);
    }
    /**
     * <code>repeated .com.baidu.stock.quote.protocbuf.Rank rank = 3;</code>
     *
     * <pre>
     *排行内容
     * </pre>
     */
    public com.baidu.stock.quote.protocbuf.RankProto.RankOrBuilder getRankOrBuilder(
        int index) {
      return rank_.get(index);
    }

    public static final int CATNAME_FIELD_NUMBER = 4;
    private java.lang.Object catName_;
    /**
     * <code>optional string catName = 4;</code>
     *
     * <pre>
     *分类名称
     * </pre>
     */
    public boolean hasCatName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string catName = 4;</code>
     *
     * <pre>
     *分类名称
     * </pre>
     */
    public java.lang.String getCatName() {
      java.lang.Object ref = catName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          catName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string catName = 4;</code>
     *
     * <pre>
     *分类名称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getCatNameBytes() {
      java.lang.Object ref = catName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        catName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CATDESC_FIELD_NUMBER = 5;
    private java.lang.Object catDesc_;
    /**
     * <code>optional string catDesc = 5;</code>
     *
     * <pre>
     *分类描述
     * </pre>
     */
    public boolean hasCatDesc() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string catDesc = 5;</code>
     *
     * <pre>
     *分类描述
     * </pre>
     */
    public java.lang.String getCatDesc() {
      java.lang.Object ref = catDesc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          catDesc_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string catDesc = 5;</code>
     *
     * <pre>
     *分类描述
     * </pre>
     */
    public com.google.protobuf.ByteString
        getCatDescBytes() {
      java.lang.Object ref = catDesc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        catDesc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      date_ = 0;
      time_ = 0;
      rank_ = java.util.Collections.emptyList();
      catName_ = "";
      catDesc_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getRankCount(); i++) {
        if (!getRank(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, date_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, time_);
      }
      for (int i = 0; i < rank_.size(); i++) {
        output.writeMessage(3, rank_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(4, getCatNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(5, getCatDescBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, date_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, time_);
      }
      for (int i = 0; i < rank_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, rank_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getCatNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getCatDescBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.baidu.stock.quote.protocbuf.RankListProto.RankList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baidu.stock.quote.protocbuf.RankListProto.RankList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baidu.stock.quote.protocbuf.RankListProto.RankList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baidu.stock.quote.protocbuf.RankListProto.RankList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baidu.stock.quote.protocbuf.RankListProto.RankList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.baidu.stock.quote.protocbuf.RankListProto.RankList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.baidu.stock.quote.protocbuf.RankListProto.RankList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.baidu.stock.quote.protocbuf.RankListProto.RankList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.baidu.stock.quote.protocbuf.RankListProto.RankList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.baidu.stock.quote.protocbuf.RankListProto.RankList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.baidu.stock.quote.protocbuf.RankListProto.RankList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.baidu.stock.quote.protocbuf.RankList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.baidu.stock.quote.protocbuf.RankList)
        com.baidu.stock.quote.protocbuf.RankListProto.RankListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.baidu.stock.quote.protocbuf.RankListProto.internal_static_com_baidu_stock_quote_protocbuf_RankList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.baidu.stock.quote.protocbuf.RankListProto.internal_static_com_baidu_stock_quote_protocbuf_RankList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.baidu.stock.quote.protocbuf.RankListProto.RankList.class, com.baidu.stock.quote.protocbuf.RankListProto.RankList.Builder.class);
      }

      // Construct using com.baidu.stock.quote.protocbuf.RankListProto.RankList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRankFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        date_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (rankBuilder_ == null) {
          rank_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          rankBuilder_.clear();
        }
        catName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        catDesc_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.baidu.stock.quote.protocbuf.RankListProto.internal_static_com_baidu_stock_quote_protocbuf_RankList_descriptor;
      }

      public com.baidu.stock.quote.protocbuf.RankListProto.RankList getDefaultInstanceForType() {
        return com.baidu.stock.quote.protocbuf.RankListProto.RankList.getDefaultInstance();
      }

      public com.baidu.stock.quote.protocbuf.RankListProto.RankList build() {
        com.baidu.stock.quote.protocbuf.RankListProto.RankList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.baidu.stock.quote.protocbuf.RankListProto.RankList buildPartial() {
        com.baidu.stock.quote.protocbuf.RankListProto.RankList result = new com.baidu.stock.quote.protocbuf.RankListProto.RankList(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.date_ = date_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.time_ = time_;
        if (rankBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            rank_ = java.util.Collections.unmodifiableList(rank_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.rank_ = rank_;
        } else {
          result.rank_ = rankBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.catName_ = catName_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.catDesc_ = catDesc_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.baidu.stock.quote.protocbuf.RankListProto.RankList) {
          return mergeFrom((com.baidu.stock.quote.protocbuf.RankListProto.RankList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.baidu.stock.quote.protocbuf.RankListProto.RankList other) {
        if (other == com.baidu.stock.quote.protocbuf.RankListProto.RankList.getDefaultInstance()) return this;
        if (other.hasDate()) {
          setDate(other.getDate());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (rankBuilder_ == null) {
          if (!other.rank_.isEmpty()) {
            if (rank_.isEmpty()) {
              rank_ = other.rank_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureRankIsMutable();
              rank_.addAll(other.rank_);
            }
            onChanged();
          }
        } else {
          if (!other.rank_.isEmpty()) {
            if (rankBuilder_.isEmpty()) {
              rankBuilder_.dispose();
              rankBuilder_ = null;
              rank_ = other.rank_;
              bitField0_ = (bitField0_ & ~0x00000004);
              rankBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRankFieldBuilder() : null;
            } else {
              rankBuilder_.addAllMessages(other.rank_);
            }
          }
        }
        if (other.hasCatName()) {
          bitField0_ |= 0x00000008;
          catName_ = other.catName_;
          onChanged();
        }
        if (other.hasCatDesc()) {
          bitField0_ |= 0x00000010;
          catDesc_ = other.catDesc_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDate()) {
          
          return false;
        }
        if (!hasTime()) {
          
          return false;
        }
        for (int i = 0; i < getRankCount(); i++) {
          if (!getRank(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.baidu.stock.quote.protocbuf.RankListProto.RankList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.baidu.stock.quote.protocbuf.RankListProto.RankList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int date_ ;
      /**
       * <code>required int32 date = 1;</code>
       *
       * <pre>
       *日期格式yyyyMMdd
       * </pre>
       */
      public boolean hasDate() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 date = 1;</code>
       *
       * <pre>
       *日期格式yyyyMMdd
       * </pre>
       */
      public int getDate() {
        return date_;
      }
      /**
       * <code>required int32 date = 1;</code>
       *
       * <pre>
       *日期格式yyyyMMdd
       * </pre>
       */
      public Builder setDate(int value) {
        bitField0_ |= 0x00000001;
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 date = 1;</code>
       *
       * <pre>
       *日期格式yyyyMMdd
       * </pre>
       */
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000001);
        date_ = 0;
        onChanged();
        return this;
      }

      private int time_ ;
      /**
       * <code>required int32 time = 2;</code>
       *
       * <pre>
       *时间格式HHmmssSSS
       * </pre>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 time = 2;</code>
       *
       * <pre>
       *时间格式HHmmssSSS
       * </pre>
       */
      public int getTime() {
        return time_;
      }
      /**
       * <code>required int32 time = 2;</code>
       *
       * <pre>
       *时间格式HHmmssSSS
       * </pre>
       */
      public Builder setTime(int value) {
        bitField0_ |= 0x00000002;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 time = 2;</code>
       *
       * <pre>
       *时间格式HHmmssSSS
       * </pre>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        time_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.baidu.stock.quote.protocbuf.RankProto.Rank> rank_ =
        java.util.Collections.emptyList();
      private void ensureRankIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          rank_ = new java.util.ArrayList<com.baidu.stock.quote.protocbuf.RankProto.Rank>(rank_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.baidu.stock.quote.protocbuf.RankProto.Rank, com.baidu.stock.quote.protocbuf.RankProto.Rank.Builder, com.baidu.stock.quote.protocbuf.RankProto.RankOrBuilder> rankBuilder_;

      /**
       * <code>repeated .com.baidu.stock.quote.protocbuf.Rank rank = 3;</code>
       *
       * <pre>
       *排行内容
       * </pre>
       */
      public java.util.List<com.baidu.stock.quote.protocbuf.RankProto.Rank> getRankList() {
        if (rankBuilder_ == null) {
          return java.util.Collections.unmodifiableList(rank_);
        } else {
          return rankBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.baidu.stock.quote.protocbuf.Rank rank = 3;</code>
       *
       * <pre>
       *排行内容
       * </pre>
       */
      public int getRankCount() {
        if (rankBuilder_ == null) {
          return rank_.size();
        } else {
          return rankBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.baidu.stock.quote.protocbuf.Rank rank = 3;</code>
       *
       * <pre>
       *排行内容
       * </pre>
       */
      public com.baidu.stock.quote.protocbuf.RankProto.Rank getRank(int index) {
        if (rankBuilder_ == null) {
          return rank_.get(index);
        } else {
          return rankBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.baidu.stock.quote.protocbuf.Rank rank = 3;</code>
       *
       * <pre>
       *排行内容
       * </pre>
       */
      public Builder setRank(
          int index, com.baidu.stock.quote.protocbuf.RankProto.Rank value) {
        if (rankBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRankIsMutable();
          rank_.set(index, value);
          onChanged();
        } else {
          rankBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.baidu.stock.quote.protocbuf.Rank rank = 3;</code>
       *
       * <pre>
       *排行内容
       * </pre>
       */
      public Builder setRank(
          int index, com.baidu.stock.quote.protocbuf.RankProto.Rank.Builder builderForValue) {
        if (rankBuilder_ == null) {
          ensureRankIsMutable();
          rank_.set(index, builderForValue.build());
          onChanged();
        } else {
          rankBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.baidu.stock.quote.protocbuf.Rank rank = 3;</code>
       *
       * <pre>
       *排行内容
       * </pre>
       */
      public Builder addRank(com.baidu.stock.quote.protocbuf.RankProto.Rank value) {
        if (rankBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRankIsMutable();
          rank_.add(value);
          onChanged();
        } else {
          rankBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.baidu.stock.quote.protocbuf.Rank rank = 3;</code>
       *
       * <pre>
       *排行内容
       * </pre>
       */
      public Builder addRank(
          int index, com.baidu.stock.quote.protocbuf.RankProto.Rank value) {
        if (rankBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRankIsMutable();
          rank_.add(index, value);
          onChanged();
        } else {
          rankBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.baidu.stock.quote.protocbuf.Rank rank = 3;</code>
       *
       * <pre>
       *排行内容
       * </pre>
       */
      public Builder addRank(
          com.baidu.stock.quote.protocbuf.RankProto.Rank.Builder builderForValue) {
        if (rankBuilder_ == null) {
          ensureRankIsMutable();
          rank_.add(builderForValue.build());
          onChanged();
        } else {
          rankBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.baidu.stock.quote.protocbuf.Rank rank = 3;</code>
       *
       * <pre>
       *排行内容
       * </pre>
       */
      public Builder addRank(
          int index, com.baidu.stock.quote.protocbuf.RankProto.Rank.Builder builderForValue) {
        if (rankBuilder_ == null) {
          ensureRankIsMutable();
          rank_.add(index, builderForValue.build());
          onChanged();
        } else {
          rankBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.baidu.stock.quote.protocbuf.Rank rank = 3;</code>
       *
       * <pre>
       *排行内容
       * </pre>
       */
      public Builder addAllRank(
          java.lang.Iterable<? extends com.baidu.stock.quote.protocbuf.RankProto.Rank> values) {
        if (rankBuilder_ == null) {
          ensureRankIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, rank_);
          onChanged();
        } else {
          rankBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.baidu.stock.quote.protocbuf.Rank rank = 3;</code>
       *
       * <pre>
       *排行内容
       * </pre>
       */
      public Builder clearRank() {
        if (rankBuilder_ == null) {
          rank_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          rankBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.baidu.stock.quote.protocbuf.Rank rank = 3;</code>
       *
       * <pre>
       *排行内容
       * </pre>
       */
      public Builder removeRank(int index) {
        if (rankBuilder_ == null) {
          ensureRankIsMutable();
          rank_.remove(index);
          onChanged();
        } else {
          rankBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.baidu.stock.quote.protocbuf.Rank rank = 3;</code>
       *
       * <pre>
       *排行内容
       * </pre>
       */
      public com.baidu.stock.quote.protocbuf.RankProto.Rank.Builder getRankBuilder(
          int index) {
        return getRankFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.baidu.stock.quote.protocbuf.Rank rank = 3;</code>
       *
       * <pre>
       *排行内容
       * </pre>
       */
      public com.baidu.stock.quote.protocbuf.RankProto.RankOrBuilder getRankOrBuilder(
          int index) {
        if (rankBuilder_ == null) {
          return rank_.get(index);  } else {
          return rankBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.baidu.stock.quote.protocbuf.Rank rank = 3;</code>
       *
       * <pre>
       *排行内容
       * </pre>
       */
      public java.util.List<? extends com.baidu.stock.quote.protocbuf.RankProto.RankOrBuilder> 
           getRankOrBuilderList() {
        if (rankBuilder_ != null) {
          return rankBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(rank_);
        }
      }
      /**
       * <code>repeated .com.baidu.stock.quote.protocbuf.Rank rank = 3;</code>
       *
       * <pre>
       *排行内容
       * </pre>
       */
      public com.baidu.stock.quote.protocbuf.RankProto.Rank.Builder addRankBuilder() {
        return getRankFieldBuilder().addBuilder(
            com.baidu.stock.quote.protocbuf.RankProto.Rank.getDefaultInstance());
      }
      /**
       * <code>repeated .com.baidu.stock.quote.protocbuf.Rank rank = 3;</code>
       *
       * <pre>
       *排行内容
       * </pre>
       */
      public com.baidu.stock.quote.protocbuf.RankProto.Rank.Builder addRankBuilder(
          int index) {
        return getRankFieldBuilder().addBuilder(
            index, com.baidu.stock.quote.protocbuf.RankProto.Rank.getDefaultInstance());
      }
      /**
       * <code>repeated .com.baidu.stock.quote.protocbuf.Rank rank = 3;</code>
       *
       * <pre>
       *排行内容
       * </pre>
       */
      public java.util.List<com.baidu.stock.quote.protocbuf.RankProto.Rank.Builder> 
           getRankBuilderList() {
        return getRankFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.baidu.stock.quote.protocbuf.RankProto.Rank, com.baidu.stock.quote.protocbuf.RankProto.Rank.Builder, com.baidu.stock.quote.protocbuf.RankProto.RankOrBuilder> 
          getRankFieldBuilder() {
        if (rankBuilder_ == null) {
          rankBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.baidu.stock.quote.protocbuf.RankProto.Rank, com.baidu.stock.quote.protocbuf.RankProto.Rank.Builder, com.baidu.stock.quote.protocbuf.RankProto.RankOrBuilder>(
                  rank_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          rank_ = null;
        }
        return rankBuilder_;
      }

      private java.lang.Object catName_ = "";
      /**
       * <code>optional string catName = 4;</code>
       *
       * <pre>
       *分类名称
       * </pre>
       */
      public boolean hasCatName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string catName = 4;</code>
       *
       * <pre>
       *分类名称
       * </pre>
       */
      public java.lang.String getCatName() {
        java.lang.Object ref = catName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            catName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string catName = 4;</code>
       *
       * <pre>
       *分类名称
       * </pre>
       */
      public com.google.protobuf.ByteString
          getCatNameBytes() {
        java.lang.Object ref = catName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          catName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string catName = 4;</code>
       *
       * <pre>
       *分类名称
       * </pre>
       */
      public Builder setCatName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        catName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string catName = 4;</code>
       *
       * <pre>
       *分类名称
       * </pre>
       */
      public Builder clearCatName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        catName_ = getDefaultInstance().getCatName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string catName = 4;</code>
       *
       * <pre>
       *分类名称
       * </pre>
       */
      public Builder setCatNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        catName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object catDesc_ = "";
      /**
       * <code>optional string catDesc = 5;</code>
       *
       * <pre>
       *分类描述
       * </pre>
       */
      public boolean hasCatDesc() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string catDesc = 5;</code>
       *
       * <pre>
       *分类描述
       * </pre>
       */
      public java.lang.String getCatDesc() {
        java.lang.Object ref = catDesc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            catDesc_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string catDesc = 5;</code>
       *
       * <pre>
       *分类描述
       * </pre>
       */
      public com.google.protobuf.ByteString
          getCatDescBytes() {
        java.lang.Object ref = catDesc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          catDesc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string catDesc = 5;</code>
       *
       * <pre>
       *分类描述
       * </pre>
       */
      public Builder setCatDesc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        catDesc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string catDesc = 5;</code>
       *
       * <pre>
       *分类描述
       * </pre>
       */
      public Builder clearCatDesc() {
        bitField0_ = (bitField0_ & ~0x00000010);
        catDesc_ = getDefaultInstance().getCatDesc();
        onChanged();
        return this;
      }
      /**
       * <code>optional string catDesc = 5;</code>
       *
       * <pre>
       *分类描述
       * </pre>
       */
      public Builder setCatDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        catDesc_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.baidu.stock.quote.protocbuf.RankList)
    }

    static {
      defaultInstance = new RankList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.baidu.stock.quote.protocbuf.RankList)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_baidu_stock_quote_protocbuf_RankList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_baidu_stock_quote_protocbuf_RankList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016RankList.proto\022\037com.baidu.stock.quote." +
      "protocbuf\032\nRank.proto\"}\n\010RankList\022\014\n\004dat" +
      "e\030\001 \002(\005\022\014\n\004time\030\002 \002(\005\0223\n\004rank\030\003 \003(\0132%.co" +
      "m.baidu.stock.quote.protocbuf.Rank\022\017\n\007ca" +
      "tName\030\004 \001(\t\022\017\n\007catDesc\030\005 \001(\tB0\n\037com.baid" +
      "u.stock.quote.protocbufB\rRankListProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.baidu.stock.quote.protocbuf.RankProto.getDescriptor(),
        }, assigner);
    internal_static_com_baidu_stock_quote_protocbuf_RankList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_baidu_stock_quote_protocbuf_RankList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_baidu_stock_quote_protocbuf_RankList_descriptor,
        new java.lang.String[] { "Date", "Time", "Rank", "CatName", "CatDesc", });
    com.baidu.stock.quote.protocbuf.RankProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
