// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockBasic.proto

package com.baidu.stock.quote.protocbuf;

public final class StockBasicProto {
  private StockBasicProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface StockBasicOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.baidu.stock.quote.protocbuf.StockBasic)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string exchange = 1;</code>
     *
     * <pre>
     *交易所
     * </pre>
     */
    boolean hasExchange();
    /**
     * <code>required string exchange = 1;</code>
     *
     * <pre>
     *交易所
     * </pre>
     */
    java.lang.String getExchange();
    /**
     * <code>required string exchange = 1;</code>
     *
     * <pre>
     *交易所
     * </pre>
     */
    com.google.protobuf.ByteString
        getExchangeBytes();

    /**
     * <code>required string stockCode = 2;</code>
     *
     * <pre>
     *证券代码
     * </pre>
     */
    boolean hasStockCode();
    /**
     * <code>required string stockCode = 2;</code>
     *
     * <pre>
     *证券代码
     * </pre>
     */
    java.lang.String getStockCode();
    /**
     * <code>required string stockCode = 2;</code>
     *
     * <pre>
     *证券代码
     * </pre>
     */
    com.google.protobuf.ByteString
        getStockCodeBytes();

    /**
     * <code>optional string stockName = 3;</code>
     *
     * <pre>
     *证券名称
     * </pre>
     */
    boolean hasStockName();
    /**
     * <code>optional string stockName = 3;</code>
     *
     * <pre>
     *证券名称
     * </pre>
     */
    java.lang.String getStockName();
    /**
     * <code>optional string stockName = 3;</code>
     *
     * <pre>
     *证券名称
     * </pre>
     */
    com.google.protobuf.ByteString
        getStockNameBytes();

    /**
     * <code>optional int32 stockStatus = 4 [default = 2];</code>
     *
     * <pre>
     *0:停盘 1:退市 2:正常 3:未上市
     * </pre>
     */
    boolean hasStockStatus();
    /**
     * <code>optional int32 stockStatus = 4 [default = 2];</code>
     *
     * <pre>
     *0:停盘 1:退市 2:正常 3:未上市
     * </pre>
     */
    int getStockStatus();

    /**
     * <code>optional int32 asset = 5;</code>
     *
     * <pre>
     *0:股票 1:期货 2:期权 3:外汇 4指数 5:场内基金 6:债券、7:认购权证 8:认沽权证 9: 牛证 10:熊证  
     *11:其他  12:表示场外 13:表示货币 14:表示B股 15:回购 16:场内的货币基金 17:港股基金
     * </pre>
     */
    boolean hasAsset();
    /**
     * <code>optional int32 asset = 5;</code>
     *
     * <pre>
     *0:股票 1:期货 2:期权 3:外汇 4指数 5:场内基金 6:债券、7:认购权证 8:认沽权证 9: 牛证 10:熊证  
     *11:其他  12:表示场外 13:表示货币 14:表示B股 15:回购 16:场内的货币基金 17:港股基金
     * </pre>
     */
    int getAsset();
  }
  /**
   * Protobuf type {@code com.baidu.stock.quote.protocbuf.StockBasic}
   */
  public static final class StockBasic extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.baidu.stock.quote.protocbuf.StockBasic)
      StockBasicOrBuilder {
    // Use StockBasic.newBuilder() to construct.
    private StockBasic(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StockBasic(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StockBasic defaultInstance;
    public static StockBasic getDefaultInstance() {
      return defaultInstance;
    }

    public StockBasic getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StockBasic(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              exchange_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              stockCode_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              stockName_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              stockStatus_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              asset_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.baidu.stock.quote.protocbuf.StockBasicProto.internal_static_com_baidu_stock_quote_protocbuf_StockBasic_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.baidu.stock.quote.protocbuf.StockBasicProto.internal_static_com_baidu_stock_quote_protocbuf_StockBasic_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.class, com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.Builder.class);
    }

    public static com.google.protobuf.Parser<StockBasic> PARSER =
        new com.google.protobuf.AbstractParser<StockBasic>() {
      public StockBasic parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StockBasic(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<StockBasic> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int EXCHANGE_FIELD_NUMBER = 1;
    private java.lang.Object exchange_;
    /**
     * <code>required string exchange = 1;</code>
     *
     * <pre>
     *交易所
     * </pre>
     */
    public boolean hasExchange() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string exchange = 1;</code>
     *
     * <pre>
     *交易所
     * </pre>
     */
    public java.lang.String getExchange() {
      java.lang.Object ref = exchange_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          exchange_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string exchange = 1;</code>
     *
     * <pre>
     *交易所
     * </pre>
     */
    public com.google.protobuf.ByteString
        getExchangeBytes() {
      java.lang.Object ref = exchange_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exchange_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STOCKCODE_FIELD_NUMBER = 2;
    private java.lang.Object stockCode_;
    /**
     * <code>required string stockCode = 2;</code>
     *
     * <pre>
     *证券代码
     * </pre>
     */
    public boolean hasStockCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string stockCode = 2;</code>
     *
     * <pre>
     *证券代码
     * </pre>
     */
    public java.lang.String getStockCode() {
      java.lang.Object ref = stockCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          stockCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string stockCode = 2;</code>
     *
     * <pre>
     *证券代码
     * </pre>
     */
    public com.google.protobuf.ByteString
        getStockCodeBytes() {
      java.lang.Object ref = stockCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stockCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STOCKNAME_FIELD_NUMBER = 3;
    private java.lang.Object stockName_;
    /**
     * <code>optional string stockName = 3;</code>
     *
     * <pre>
     *证券名称
     * </pre>
     */
    public boolean hasStockName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string stockName = 3;</code>
     *
     * <pre>
     *证券名称
     * </pre>
     */
    public java.lang.String getStockName() {
      java.lang.Object ref = stockName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          stockName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string stockName = 3;</code>
     *
     * <pre>
     *证券名称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getStockNameBytes() {
      java.lang.Object ref = stockName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stockName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STOCKSTATUS_FIELD_NUMBER = 4;
    private int stockStatus_;
    /**
     * <code>optional int32 stockStatus = 4 [default = 2];</code>
     *
     * <pre>
     *0:停盘 1:退市 2:正常 3:未上市
     * </pre>
     */
    public boolean hasStockStatus() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 stockStatus = 4 [default = 2];</code>
     *
     * <pre>
     *0:停盘 1:退市 2:正常 3:未上市
     * </pre>
     */
    public int getStockStatus() {
      return stockStatus_;
    }

    public static final int ASSET_FIELD_NUMBER = 5;
    private int asset_;
    /**
     * <code>optional int32 asset = 5;</code>
     *
     * <pre>
     *0:股票 1:期货 2:期权 3:外汇 4指数 5:场内基金 6:债券、7:认购权证 8:认沽权证 9: 牛证 10:熊证  
     *11:其他  12:表示场外 13:表示货币 14:表示B股 15:回购 16:场内的货币基金 17:港股基金
     * </pre>
     */
    public boolean hasAsset() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 asset = 5;</code>
     *
     * <pre>
     *0:股票 1:期货 2:期权 3:外汇 4指数 5:场内基金 6:债券、7:认购权证 8:认沽权证 9: 牛证 10:熊证  
     *11:其他  12:表示场外 13:表示货币 14:表示B股 15:回购 16:场内的货币基金 17:港股基金
     * </pre>
     */
    public int getAsset() {
      return asset_;
    }

    private void initFields() {
      exchange_ = "";
      stockCode_ = "";
      stockName_ = "";
      stockStatus_ = 2;
      asset_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasExchange()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStockCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getExchangeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getStockCodeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getStockNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, stockStatus_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, asset_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getExchangeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getStockCodeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getStockNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, stockStatus_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, asset_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.baidu.stock.quote.protocbuf.StockBasic}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.baidu.stock.quote.protocbuf.StockBasic)
        com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasicOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.baidu.stock.quote.protocbuf.StockBasicProto.internal_static_com_baidu_stock_quote_protocbuf_StockBasic_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.baidu.stock.quote.protocbuf.StockBasicProto.internal_static_com_baidu_stock_quote_protocbuf_StockBasic_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.class, com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.Builder.class);
      }

      // Construct using com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        exchange_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        stockCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        stockName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        stockStatus_ = 2;
        bitField0_ = (bitField0_ & ~0x00000008);
        asset_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.baidu.stock.quote.protocbuf.StockBasicProto.internal_static_com_baidu_stock_quote_protocbuf_StockBasic_descriptor;
      }

      public com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic getDefaultInstanceForType() {
        return com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.getDefaultInstance();
      }

      public com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic build() {
        com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic buildPartial() {
        com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic result = new com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.exchange_ = exchange_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.stockCode_ = stockCode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.stockName_ = stockName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.stockStatus_ = stockStatus_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.asset_ = asset_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic) {
          return mergeFrom((com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic other) {
        if (other == com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.getDefaultInstance()) return this;
        if (other.hasExchange()) {
          bitField0_ |= 0x00000001;
          exchange_ = other.exchange_;
          onChanged();
        }
        if (other.hasStockCode()) {
          bitField0_ |= 0x00000002;
          stockCode_ = other.stockCode_;
          onChanged();
        }
        if (other.hasStockName()) {
          bitField0_ |= 0x00000004;
          stockName_ = other.stockName_;
          onChanged();
        }
        if (other.hasStockStatus()) {
          setStockStatus(other.getStockStatus());
        }
        if (other.hasAsset()) {
          setAsset(other.getAsset());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasExchange()) {
          
          return false;
        }
        if (!hasStockCode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object exchange_ = "";
      /**
       * <code>required string exchange = 1;</code>
       *
       * <pre>
       *交易所
       * </pre>
       */
      public boolean hasExchange() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string exchange = 1;</code>
       *
       * <pre>
       *交易所
       * </pre>
       */
      public java.lang.String getExchange() {
        java.lang.Object ref = exchange_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            exchange_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string exchange = 1;</code>
       *
       * <pre>
       *交易所
       * </pre>
       */
      public com.google.protobuf.ByteString
          getExchangeBytes() {
        java.lang.Object ref = exchange_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          exchange_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string exchange = 1;</code>
       *
       * <pre>
       *交易所
       * </pre>
       */
      public Builder setExchange(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        exchange_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string exchange = 1;</code>
       *
       * <pre>
       *交易所
       * </pre>
       */
      public Builder clearExchange() {
        bitField0_ = (bitField0_ & ~0x00000001);
        exchange_ = getDefaultInstance().getExchange();
        onChanged();
        return this;
      }
      /**
       * <code>required string exchange = 1;</code>
       *
       * <pre>
       *交易所
       * </pre>
       */
      public Builder setExchangeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        exchange_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object stockCode_ = "";
      /**
       * <code>required string stockCode = 2;</code>
       *
       * <pre>
       *证券代码
       * </pre>
       */
      public boolean hasStockCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string stockCode = 2;</code>
       *
       * <pre>
       *证券代码
       * </pre>
       */
      public java.lang.String getStockCode() {
        java.lang.Object ref = stockCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            stockCode_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string stockCode = 2;</code>
       *
       * <pre>
       *证券代码
       * </pre>
       */
      public com.google.protobuf.ByteString
          getStockCodeBytes() {
        java.lang.Object ref = stockCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stockCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string stockCode = 2;</code>
       *
       * <pre>
       *证券代码
       * </pre>
       */
      public Builder setStockCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        stockCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string stockCode = 2;</code>
       *
       * <pre>
       *证券代码
       * </pre>
       */
      public Builder clearStockCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        stockCode_ = getDefaultInstance().getStockCode();
        onChanged();
        return this;
      }
      /**
       * <code>required string stockCode = 2;</code>
       *
       * <pre>
       *证券代码
       * </pre>
       */
      public Builder setStockCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        stockCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object stockName_ = "";
      /**
       * <code>optional string stockName = 3;</code>
       *
       * <pre>
       *证券名称
       * </pre>
       */
      public boolean hasStockName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string stockName = 3;</code>
       *
       * <pre>
       *证券名称
       * </pre>
       */
      public java.lang.String getStockName() {
        java.lang.Object ref = stockName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            stockName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string stockName = 3;</code>
       *
       * <pre>
       *证券名称
       * </pre>
       */
      public com.google.protobuf.ByteString
          getStockNameBytes() {
        java.lang.Object ref = stockName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stockName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string stockName = 3;</code>
       *
       * <pre>
       *证券名称
       * </pre>
       */
      public Builder setStockName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        stockName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string stockName = 3;</code>
       *
       * <pre>
       *证券名称
       * </pre>
       */
      public Builder clearStockName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        stockName_ = getDefaultInstance().getStockName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string stockName = 3;</code>
       *
       * <pre>
       *证券名称
       * </pre>
       */
      public Builder setStockNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        stockName_ = value;
        onChanged();
        return this;
      }

      private int stockStatus_ = 2;
      /**
       * <code>optional int32 stockStatus = 4 [default = 2];</code>
       *
       * <pre>
       *0:停盘 1:退市 2:正常 3:未上市
       * </pre>
       */
      public boolean hasStockStatus() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 stockStatus = 4 [default = 2];</code>
       *
       * <pre>
       *0:停盘 1:退市 2:正常 3:未上市
       * </pre>
       */
      public int getStockStatus() {
        return stockStatus_;
      }
      /**
       * <code>optional int32 stockStatus = 4 [default = 2];</code>
       *
       * <pre>
       *0:停盘 1:退市 2:正常 3:未上市
       * </pre>
       */
      public Builder setStockStatus(int value) {
        bitField0_ |= 0x00000008;
        stockStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 stockStatus = 4 [default = 2];</code>
       *
       * <pre>
       *0:停盘 1:退市 2:正常 3:未上市
       * </pre>
       */
      public Builder clearStockStatus() {
        bitField0_ = (bitField0_ & ~0x00000008);
        stockStatus_ = 2;
        onChanged();
        return this;
      }

      private int asset_ ;
      /**
       * <code>optional int32 asset = 5;</code>
       *
       * <pre>
       *0:股票 1:期货 2:期权 3:外汇 4指数 5:场内基金 6:债券、7:认购权证 8:认沽权证 9: 牛证 10:熊证  
       *11:其他  12:表示场外 13:表示货币 14:表示B股 15:回购 16:场内的货币基金 17:港股基金
       * </pre>
       */
      public boolean hasAsset() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 asset = 5;</code>
       *
       * <pre>
       *0:股票 1:期货 2:期权 3:外汇 4指数 5:场内基金 6:债券、7:认购权证 8:认沽权证 9: 牛证 10:熊证  
       *11:其他  12:表示场外 13:表示货币 14:表示B股 15:回购 16:场内的货币基金 17:港股基金
       * </pre>
       */
      public int getAsset() {
        return asset_;
      }
      /**
       * <code>optional int32 asset = 5;</code>
       *
       * <pre>
       *0:股票 1:期货 2:期权 3:外汇 4指数 5:场内基金 6:债券、7:认购权证 8:认沽权证 9: 牛证 10:熊证  
       *11:其他  12:表示场外 13:表示货币 14:表示B股 15:回购 16:场内的货币基金 17:港股基金
       * </pre>
       */
      public Builder setAsset(int value) {
        bitField0_ |= 0x00000010;
        asset_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 asset = 5;</code>
       *
       * <pre>
       *0:股票 1:期货 2:期权 3:外汇 4指数 5:场内基金 6:债券、7:认购权证 8:认沽权证 9: 牛证 10:熊证  
       *11:其他  12:表示场外 13:表示货币 14:表示B股 15:回购 16:场内的货币基金 17:港股基金
       * </pre>
       */
      public Builder clearAsset() {
        bitField0_ = (bitField0_ & ~0x00000010);
        asset_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.baidu.stock.quote.protocbuf.StockBasic)
    }

    static {
      defaultInstance = new StockBasic(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.baidu.stock.quote.protocbuf.StockBasic)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_baidu_stock_quote_protocbuf_StockBasic_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_baidu_stock_quote_protocbuf_StockBasic_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020StockBasic.proto\022\037com.baidu.stock.quot" +
      "e.protocbuf\"k\n\nStockBasic\022\020\n\010exchange\030\001 " +
      "\002(\t\022\021\n\tstockCode\030\002 \002(\t\022\021\n\tstockName\030\003 \001(" +
      "\t\022\026\n\013stockStatus\030\004 \001(\005:\0012\022\r\n\005asset\030\005 \001(\005" +
      "B2\n\037com.baidu.stock.quote.protocbufB\017Sto" +
      "ckBasicProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_baidu_stock_quote_protocbuf_StockBasic_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_baidu_stock_quote_protocbuf_StockBasic_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_baidu_stock_quote_protocbuf_StockBasic_descriptor,
        new java.lang.String[] { "Exchange", "StockCode", "StockName", "StockStatus", "Asset", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
