// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: XYAFinacialInfo.proto

package com.baidu.stock.quote.protocbuf;

public final class XYAFinacialInfoProto {
  private XYAFinacialInfoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface XYAFinacialInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.baidu.stock.quote.protocbuf.XYAFinacialInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .com.baidu.stock.quote.protocbuf.StockBasic security = 1;</code>
     *
     * <pre>
     * 股票信息
     * </pre>
     */
    boolean hasSecurity();
    /**
     * <code>required .com.baidu.stock.quote.protocbuf.StockBasic security = 1;</code>
     *
     * <pre>
     * 股票信息
     * </pre>
     */
    com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic getSecurity();
    /**
     * <code>required .com.baidu.stock.quote.protocbuf.StockBasic security = 1;</code>
     *
     * <pre>
     * 股票信息
     * </pre>
     */
    com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasicOrBuilder getSecurityOrBuilder();

    /**
     * <code>optional int64 totalAmount = 2;</code>
     *
     * <pre>
     * 总股本 TOTALSHARE,
     * </pre>
     */
    boolean hasTotalAmount();
    /**
     * <code>optional int64 totalAmount = 2;</code>
     *
     * <pre>
     * 总股本 TOTALSHARE,
     * </pre>
     */
    long getTotalAmount();

    /**
     * <code>optional int64 AAmount = 3;</code>
     *
     * <pre>
     * 流通A股  ATOTALSHARE
     * </pre>
     */
    boolean hasAAmount();
    /**
     * <code>optional int64 AAmount = 3;</code>
     *
     * <pre>
     * 流通A股  ATOTALSHARE
     * </pre>
     */
    long getAAmount();

    /**
     * <code>optional float netAssets = 4;</code>
     *
     * <pre>
     * 每股净资产 f031n_0216/f007n_0629
     * </pre>
     */
    boolean hasNetAssets();
    /**
     * <code>optional float netAssets = 4;</code>
     *
     * <pre>
     * 每股净资产 f031n_0216/f007n_0629
     * </pre>
     */
    float getNetAssets();

    /**
     * <code>optional float stockProfit = 5;</code>
     *
     * <pre>
     * 每股收益 = 当期净利润 / 总股本  f029n_0216/ f007n_0629
     * </pre>
     */
    boolean hasStockProfit();
    /**
     * <code>optional float stockProfit = 5;</code>
     *
     * <pre>
     * 每股收益 = 当期净利润 / 总股本  f029n_0216/ f007n_0629
     * </pre>
     */
    float getStockProfit();

    /**
     * <code>optional float sellAmountPS = 6;</code>
     *
     * <pre>
     * 每股销售额  f017n_0351
     * </pre>
     */
    boolean hasSellAmountPS();
    /**
     * <code>optional float sellAmountPS = 6;</code>
     *
     * <pre>
     * 每股销售额  f017n_0351
     * </pre>
     */
    float getSellAmountPS();

    /**
     * <code>optional int32 date = 7;</code>
     *
     * <pre>
     * 财报日期 
     * </pre>
     */
    boolean hasDate();
    /**
     * <code>optional int32 date = 7;</code>
     *
     * <pre>
     * 财报日期 
     * </pre>
     */
    int getDate();

    /**
     * <code>optional float LYR = 8;</code>
     *
     * <pre>
     *去年度净利润
     * </pre>
     */
    boolean hasLYR();
    /**
     * <code>optional float LYR = 8;</code>
     *
     * <pre>
     *去年度净利润
     * </pre>
     */
    float getLYR();

    /**
     * <code>optional float TTM = 9;</code>
     *
     * <pre>
     *近12个月净利润
     * </pre>
     */
    boolean hasTTM();
    /**
     * <code>optional float TTM = 9;</code>
     *
     * <pre>
     *近12个月净利润
     * </pre>
     */
    float getTTM();

    /**
     * <code>optional float MRQ = 10;</code>
     *
     * <pre>
     *最新年化净利润
     * </pre>
     */
    boolean hasMRQ();
    /**
     * <code>optional float MRQ = 10;</code>
     *
     * <pre>
     *最新年化净利润
     * </pre>
     */
    float getMRQ();
  }
  /**
   * Protobuf type {@code com.baidu.stock.quote.protocbuf.XYAFinacialInfo}
   *
   * <pre>
   * 指标计算财务数据
   * </pre>
   */
  public static final class XYAFinacialInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.baidu.stock.quote.protocbuf.XYAFinacialInfo)
      XYAFinacialInfoOrBuilder {
    // Use XYAFinacialInfo.newBuilder() to construct.
    private XYAFinacialInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private XYAFinacialInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final XYAFinacialInfo defaultInstance;
    public static XYAFinacialInfo getDefaultInstance() {
      return defaultInstance;
    }

    public XYAFinacialInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private XYAFinacialInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = security_.toBuilder();
              }
              security_ = input.readMessage(com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(security_);
                security_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              totalAmount_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              aAmount_ = input.readInt64();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              netAssets_ = input.readFloat();
              break;
            }
            case 45: {
              bitField0_ |= 0x00000010;
              stockProfit_ = input.readFloat();
              break;
            }
            case 53: {
              bitField0_ |= 0x00000020;
              sellAmountPS_ = input.readFloat();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              date_ = input.readInt32();
              break;
            }
            case 69: {
              bitField0_ |= 0x00000080;
              lYR_ = input.readFloat();
              break;
            }
            case 77: {
              bitField0_ |= 0x00000100;
              tTM_ = input.readFloat();
              break;
            }
            case 85: {
              bitField0_ |= 0x00000200;
              mRQ_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.baidu.stock.quote.protocbuf.XYAFinacialInfoProto.internal_static_com_baidu_stock_quote_protocbuf_XYAFinacialInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.baidu.stock.quote.protocbuf.XYAFinacialInfoProto.internal_static_com_baidu_stock_quote_protocbuf_XYAFinacialInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.baidu.stock.quote.protocbuf.XYAFinacialInfoProto.XYAFinacialInfo.class, com.baidu.stock.quote.protocbuf.XYAFinacialInfoProto.XYAFinacialInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<XYAFinacialInfo> PARSER =
        new com.google.protobuf.AbstractParser<XYAFinacialInfo>() {
      public XYAFinacialInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new XYAFinacialInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<XYAFinacialInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SECURITY_FIELD_NUMBER = 1;
    private com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic security_;
    /**
     * <code>required .com.baidu.stock.quote.protocbuf.StockBasic security = 1;</code>
     *
     * <pre>
     * 股票信息
     * </pre>
     */
    public boolean hasSecurity() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.baidu.stock.quote.protocbuf.StockBasic security = 1;</code>
     *
     * <pre>
     * 股票信息
     * </pre>
     */
    public com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic getSecurity() {
      return security_;
    }
    /**
     * <code>required .com.baidu.stock.quote.protocbuf.StockBasic security = 1;</code>
     *
     * <pre>
     * 股票信息
     * </pre>
     */
    public com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasicOrBuilder getSecurityOrBuilder() {
      return security_;
    }

    public static final int TOTALAMOUNT_FIELD_NUMBER = 2;
    private long totalAmount_;
    /**
     * <code>optional int64 totalAmount = 2;</code>
     *
     * <pre>
     * 总股本 TOTALSHARE,
     * </pre>
     */
    public boolean hasTotalAmount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 totalAmount = 2;</code>
     *
     * <pre>
     * 总股本 TOTALSHARE,
     * </pre>
     */
    public long getTotalAmount() {
      return totalAmount_;
    }

    public static final int AAMOUNT_FIELD_NUMBER = 3;
    private long aAmount_;
    /**
     * <code>optional int64 AAmount = 3;</code>
     *
     * <pre>
     * 流通A股  ATOTALSHARE
     * </pre>
     */
    public boolean hasAAmount() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 AAmount = 3;</code>
     *
     * <pre>
     * 流通A股  ATOTALSHARE
     * </pre>
     */
    public long getAAmount() {
      return aAmount_;
    }

    public static final int NETASSETS_FIELD_NUMBER = 4;
    private float netAssets_;
    /**
     * <code>optional float netAssets = 4;</code>
     *
     * <pre>
     * 每股净资产 f031n_0216/f007n_0629
     * </pre>
     */
    public boolean hasNetAssets() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional float netAssets = 4;</code>
     *
     * <pre>
     * 每股净资产 f031n_0216/f007n_0629
     * </pre>
     */
    public float getNetAssets() {
      return netAssets_;
    }

    public static final int STOCKPROFIT_FIELD_NUMBER = 5;
    private float stockProfit_;
    /**
     * <code>optional float stockProfit = 5;</code>
     *
     * <pre>
     * 每股收益 = 当期净利润 / 总股本  f029n_0216/ f007n_0629
     * </pre>
     */
    public boolean hasStockProfit() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional float stockProfit = 5;</code>
     *
     * <pre>
     * 每股收益 = 当期净利润 / 总股本  f029n_0216/ f007n_0629
     * </pre>
     */
    public float getStockProfit() {
      return stockProfit_;
    }

    public static final int SELLAMOUNTPS_FIELD_NUMBER = 6;
    private float sellAmountPS_;
    /**
     * <code>optional float sellAmountPS = 6;</code>
     *
     * <pre>
     * 每股销售额  f017n_0351
     * </pre>
     */
    public boolean hasSellAmountPS() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional float sellAmountPS = 6;</code>
     *
     * <pre>
     * 每股销售额  f017n_0351
     * </pre>
     */
    public float getSellAmountPS() {
      return sellAmountPS_;
    }

    public static final int DATE_FIELD_NUMBER = 7;
    private int date_;
    /**
     * <code>optional int32 date = 7;</code>
     *
     * <pre>
     * 财报日期 
     * </pre>
     */
    public boolean hasDate() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 date = 7;</code>
     *
     * <pre>
     * 财报日期 
     * </pre>
     */
    public int getDate() {
      return date_;
    }

    public static final int LYR_FIELD_NUMBER = 8;
    private float lYR_;
    /**
     * <code>optional float LYR = 8;</code>
     *
     * <pre>
     *去年度净利润
     * </pre>
     */
    public boolean hasLYR() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional float LYR = 8;</code>
     *
     * <pre>
     *去年度净利润
     * </pre>
     */
    public float getLYR() {
      return lYR_;
    }

    public static final int TTM_FIELD_NUMBER = 9;
    private float tTM_;
    /**
     * <code>optional float TTM = 9;</code>
     *
     * <pre>
     *近12个月净利润
     * </pre>
     */
    public boolean hasTTM() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional float TTM = 9;</code>
     *
     * <pre>
     *近12个月净利润
     * </pre>
     */
    public float getTTM() {
      return tTM_;
    }

    public static final int MRQ_FIELD_NUMBER = 10;
    private float mRQ_;
    /**
     * <code>optional float MRQ = 10;</code>
     *
     * <pre>
     *最新年化净利润
     * </pre>
     */
    public boolean hasMRQ() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional float MRQ = 10;</code>
     *
     * <pre>
     *最新年化净利润
     * </pre>
     */
    public float getMRQ() {
      return mRQ_;
    }

    private void initFields() {
      security_ = com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.getDefaultInstance();
      totalAmount_ = 0L;
      aAmount_ = 0L;
      netAssets_ = 0F;
      stockProfit_ = 0F;
      sellAmountPS_ = 0F;
      date_ = 0;
      lYR_ = 0F;
      tTM_ = 0F;
      mRQ_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSecurity()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getSecurity().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, security_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, totalAmount_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, aAmount_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, netAssets_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeFloat(5, stockProfit_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeFloat(6, sellAmountPS_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, date_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeFloat(8, lYR_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeFloat(9, tTM_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeFloat(10, mRQ_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, security_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, totalAmount_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, aAmount_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, netAssets_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, stockProfit_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, sellAmountPS_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, date_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(8, lYR_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(9, tTM_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(10, mRQ_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.baidu.stock.quote.protocbuf.XYAFinacialInfoProto.XYAFinacialInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baidu.stock.quote.protocbuf.XYAFinacialInfoProto.XYAFinacialInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baidu.stock.quote.protocbuf.XYAFinacialInfoProto.XYAFinacialInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baidu.stock.quote.protocbuf.XYAFinacialInfoProto.XYAFinacialInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baidu.stock.quote.protocbuf.XYAFinacialInfoProto.XYAFinacialInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.baidu.stock.quote.protocbuf.XYAFinacialInfoProto.XYAFinacialInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.baidu.stock.quote.protocbuf.XYAFinacialInfoProto.XYAFinacialInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.baidu.stock.quote.protocbuf.XYAFinacialInfoProto.XYAFinacialInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.baidu.stock.quote.protocbuf.XYAFinacialInfoProto.XYAFinacialInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.baidu.stock.quote.protocbuf.XYAFinacialInfoProto.XYAFinacialInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.baidu.stock.quote.protocbuf.XYAFinacialInfoProto.XYAFinacialInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.baidu.stock.quote.protocbuf.XYAFinacialInfo}
     *
     * <pre>
     * 指标计算财务数据
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.baidu.stock.quote.protocbuf.XYAFinacialInfo)
        com.baidu.stock.quote.protocbuf.XYAFinacialInfoProto.XYAFinacialInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.baidu.stock.quote.protocbuf.XYAFinacialInfoProto.internal_static_com_baidu_stock_quote_protocbuf_XYAFinacialInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.baidu.stock.quote.protocbuf.XYAFinacialInfoProto.internal_static_com_baidu_stock_quote_protocbuf_XYAFinacialInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.baidu.stock.quote.protocbuf.XYAFinacialInfoProto.XYAFinacialInfo.class, com.baidu.stock.quote.protocbuf.XYAFinacialInfoProto.XYAFinacialInfo.Builder.class);
      }

      // Construct using com.baidu.stock.quote.protocbuf.XYAFinacialInfoProto.XYAFinacialInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSecurityFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (securityBuilder_ == null) {
          security_ = com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.getDefaultInstance();
        } else {
          securityBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        totalAmount_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        aAmount_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        netAssets_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        stockProfit_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000010);
        sellAmountPS_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000020);
        date_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        lYR_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000080);
        tTM_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000100);
        mRQ_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.baidu.stock.quote.protocbuf.XYAFinacialInfoProto.internal_static_com_baidu_stock_quote_protocbuf_XYAFinacialInfo_descriptor;
      }

      public com.baidu.stock.quote.protocbuf.XYAFinacialInfoProto.XYAFinacialInfo getDefaultInstanceForType() {
        return com.baidu.stock.quote.protocbuf.XYAFinacialInfoProto.XYAFinacialInfo.getDefaultInstance();
      }

      public com.baidu.stock.quote.protocbuf.XYAFinacialInfoProto.XYAFinacialInfo build() {
        com.baidu.stock.quote.protocbuf.XYAFinacialInfoProto.XYAFinacialInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.baidu.stock.quote.protocbuf.XYAFinacialInfoProto.XYAFinacialInfo buildPartial() {
        com.baidu.stock.quote.protocbuf.XYAFinacialInfoProto.XYAFinacialInfo result = new com.baidu.stock.quote.protocbuf.XYAFinacialInfoProto.XYAFinacialInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (securityBuilder_ == null) {
          result.security_ = security_;
        } else {
          result.security_ = securityBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.totalAmount_ = totalAmount_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.aAmount_ = aAmount_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.netAssets_ = netAssets_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.stockProfit_ = stockProfit_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.sellAmountPS_ = sellAmountPS_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.date_ = date_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.lYR_ = lYR_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.tTM_ = tTM_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.mRQ_ = mRQ_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.baidu.stock.quote.protocbuf.XYAFinacialInfoProto.XYAFinacialInfo) {
          return mergeFrom((com.baidu.stock.quote.protocbuf.XYAFinacialInfoProto.XYAFinacialInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.baidu.stock.quote.protocbuf.XYAFinacialInfoProto.XYAFinacialInfo other) {
        if (other == com.baidu.stock.quote.protocbuf.XYAFinacialInfoProto.XYAFinacialInfo.getDefaultInstance()) return this;
        if (other.hasSecurity()) {
          mergeSecurity(other.getSecurity());
        }
        if (other.hasTotalAmount()) {
          setTotalAmount(other.getTotalAmount());
        }
        if (other.hasAAmount()) {
          setAAmount(other.getAAmount());
        }
        if (other.hasNetAssets()) {
          setNetAssets(other.getNetAssets());
        }
        if (other.hasStockProfit()) {
          setStockProfit(other.getStockProfit());
        }
        if (other.hasSellAmountPS()) {
          setSellAmountPS(other.getSellAmountPS());
        }
        if (other.hasDate()) {
          setDate(other.getDate());
        }
        if (other.hasLYR()) {
          setLYR(other.getLYR());
        }
        if (other.hasTTM()) {
          setTTM(other.getTTM());
        }
        if (other.hasMRQ()) {
          setMRQ(other.getMRQ());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSecurity()) {
          
          return false;
        }
        if (!getSecurity().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.baidu.stock.quote.protocbuf.XYAFinacialInfoProto.XYAFinacialInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.baidu.stock.quote.protocbuf.XYAFinacialInfoProto.XYAFinacialInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic security_ = com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic, com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.Builder, com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasicOrBuilder> securityBuilder_;
      /**
       * <code>required .com.baidu.stock.quote.protocbuf.StockBasic security = 1;</code>
       *
       * <pre>
       * 股票信息
       * </pre>
       */
      public boolean hasSecurity() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.baidu.stock.quote.protocbuf.StockBasic security = 1;</code>
       *
       * <pre>
       * 股票信息
       * </pre>
       */
      public com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic getSecurity() {
        if (securityBuilder_ == null) {
          return security_;
        } else {
          return securityBuilder_.getMessage();
        }
      }
      /**
       * <code>required .com.baidu.stock.quote.protocbuf.StockBasic security = 1;</code>
       *
       * <pre>
       * 股票信息
       * </pre>
       */
      public Builder setSecurity(com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic value) {
        if (securityBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          security_ = value;
          onChanged();
        } else {
          securityBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.baidu.stock.quote.protocbuf.StockBasic security = 1;</code>
       *
       * <pre>
       * 股票信息
       * </pre>
       */
      public Builder setSecurity(
          com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.Builder builderForValue) {
        if (securityBuilder_ == null) {
          security_ = builderForValue.build();
          onChanged();
        } else {
          securityBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.baidu.stock.quote.protocbuf.StockBasic security = 1;</code>
       *
       * <pre>
       * 股票信息
       * </pre>
       */
      public Builder mergeSecurity(com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic value) {
        if (securityBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              security_ != com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.getDefaultInstance()) {
            security_ =
              com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.newBuilder(security_).mergeFrom(value).buildPartial();
          } else {
            security_ = value;
          }
          onChanged();
        } else {
          securityBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.baidu.stock.quote.protocbuf.StockBasic security = 1;</code>
       *
       * <pre>
       * 股票信息
       * </pre>
       */
      public Builder clearSecurity() {
        if (securityBuilder_ == null) {
          security_ = com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.getDefaultInstance();
          onChanged();
        } else {
          securityBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .com.baidu.stock.quote.protocbuf.StockBasic security = 1;</code>
       *
       * <pre>
       * 股票信息
       * </pre>
       */
      public com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.Builder getSecurityBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getSecurityFieldBuilder().getBuilder();
      }
      /**
       * <code>required .com.baidu.stock.quote.protocbuf.StockBasic security = 1;</code>
       *
       * <pre>
       * 股票信息
       * </pre>
       */
      public com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasicOrBuilder getSecurityOrBuilder() {
        if (securityBuilder_ != null) {
          return securityBuilder_.getMessageOrBuilder();
        } else {
          return security_;
        }
      }
      /**
       * <code>required .com.baidu.stock.quote.protocbuf.StockBasic security = 1;</code>
       *
       * <pre>
       * 股票信息
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic, com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.Builder, com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasicOrBuilder> 
          getSecurityFieldBuilder() {
        if (securityBuilder_ == null) {
          securityBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic, com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasic.Builder, com.baidu.stock.quote.protocbuf.StockBasicProto.StockBasicOrBuilder>(
                  getSecurity(),
                  getParentForChildren(),
                  isClean());
          security_ = null;
        }
        return securityBuilder_;
      }

      private long totalAmount_ ;
      /**
       * <code>optional int64 totalAmount = 2;</code>
       *
       * <pre>
       * 总股本 TOTALSHARE,
       * </pre>
       */
      public boolean hasTotalAmount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 totalAmount = 2;</code>
       *
       * <pre>
       * 总股本 TOTALSHARE,
       * </pre>
       */
      public long getTotalAmount() {
        return totalAmount_;
      }
      /**
       * <code>optional int64 totalAmount = 2;</code>
       *
       * <pre>
       * 总股本 TOTALSHARE,
       * </pre>
       */
      public Builder setTotalAmount(long value) {
        bitField0_ |= 0x00000002;
        totalAmount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 totalAmount = 2;</code>
       *
       * <pre>
       * 总股本 TOTALSHARE,
       * </pre>
       */
      public Builder clearTotalAmount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        totalAmount_ = 0L;
        onChanged();
        return this;
      }

      private long aAmount_ ;
      /**
       * <code>optional int64 AAmount = 3;</code>
       *
       * <pre>
       * 流通A股  ATOTALSHARE
       * </pre>
       */
      public boolean hasAAmount() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 AAmount = 3;</code>
       *
       * <pre>
       * 流通A股  ATOTALSHARE
       * </pre>
       */
      public long getAAmount() {
        return aAmount_;
      }
      /**
       * <code>optional int64 AAmount = 3;</code>
       *
       * <pre>
       * 流通A股  ATOTALSHARE
       * </pre>
       */
      public Builder setAAmount(long value) {
        bitField0_ |= 0x00000004;
        aAmount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 AAmount = 3;</code>
       *
       * <pre>
       * 流通A股  ATOTALSHARE
       * </pre>
       */
      public Builder clearAAmount() {
        bitField0_ = (bitField0_ & ~0x00000004);
        aAmount_ = 0L;
        onChanged();
        return this;
      }

      private float netAssets_ ;
      /**
       * <code>optional float netAssets = 4;</code>
       *
       * <pre>
       * 每股净资产 f031n_0216/f007n_0629
       * </pre>
       */
      public boolean hasNetAssets() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional float netAssets = 4;</code>
       *
       * <pre>
       * 每股净资产 f031n_0216/f007n_0629
       * </pre>
       */
      public float getNetAssets() {
        return netAssets_;
      }
      /**
       * <code>optional float netAssets = 4;</code>
       *
       * <pre>
       * 每股净资产 f031n_0216/f007n_0629
       * </pre>
       */
      public Builder setNetAssets(float value) {
        bitField0_ |= 0x00000008;
        netAssets_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float netAssets = 4;</code>
       *
       * <pre>
       * 每股净资产 f031n_0216/f007n_0629
       * </pre>
       */
      public Builder clearNetAssets() {
        bitField0_ = (bitField0_ & ~0x00000008);
        netAssets_ = 0F;
        onChanged();
        return this;
      }

      private float stockProfit_ ;
      /**
       * <code>optional float stockProfit = 5;</code>
       *
       * <pre>
       * 每股收益 = 当期净利润 / 总股本  f029n_0216/ f007n_0629
       * </pre>
       */
      public boolean hasStockProfit() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional float stockProfit = 5;</code>
       *
       * <pre>
       * 每股收益 = 当期净利润 / 总股本  f029n_0216/ f007n_0629
       * </pre>
       */
      public float getStockProfit() {
        return stockProfit_;
      }
      /**
       * <code>optional float stockProfit = 5;</code>
       *
       * <pre>
       * 每股收益 = 当期净利润 / 总股本  f029n_0216/ f007n_0629
       * </pre>
       */
      public Builder setStockProfit(float value) {
        bitField0_ |= 0x00000010;
        stockProfit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float stockProfit = 5;</code>
       *
       * <pre>
       * 每股收益 = 当期净利润 / 总股本  f029n_0216/ f007n_0629
       * </pre>
       */
      public Builder clearStockProfit() {
        bitField0_ = (bitField0_ & ~0x00000010);
        stockProfit_ = 0F;
        onChanged();
        return this;
      }

      private float sellAmountPS_ ;
      /**
       * <code>optional float sellAmountPS = 6;</code>
       *
       * <pre>
       * 每股销售额  f017n_0351
       * </pre>
       */
      public boolean hasSellAmountPS() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional float sellAmountPS = 6;</code>
       *
       * <pre>
       * 每股销售额  f017n_0351
       * </pre>
       */
      public float getSellAmountPS() {
        return sellAmountPS_;
      }
      /**
       * <code>optional float sellAmountPS = 6;</code>
       *
       * <pre>
       * 每股销售额  f017n_0351
       * </pre>
       */
      public Builder setSellAmountPS(float value) {
        bitField0_ |= 0x00000020;
        sellAmountPS_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float sellAmountPS = 6;</code>
       *
       * <pre>
       * 每股销售额  f017n_0351
       * </pre>
       */
      public Builder clearSellAmountPS() {
        bitField0_ = (bitField0_ & ~0x00000020);
        sellAmountPS_ = 0F;
        onChanged();
        return this;
      }

      private int date_ ;
      /**
       * <code>optional int32 date = 7;</code>
       *
       * <pre>
       * 财报日期 
       * </pre>
       */
      public boolean hasDate() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 date = 7;</code>
       *
       * <pre>
       * 财报日期 
       * </pre>
       */
      public int getDate() {
        return date_;
      }
      /**
       * <code>optional int32 date = 7;</code>
       *
       * <pre>
       * 财报日期 
       * </pre>
       */
      public Builder setDate(int value) {
        bitField0_ |= 0x00000040;
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 date = 7;</code>
       *
       * <pre>
       * 财报日期 
       * </pre>
       */
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000040);
        date_ = 0;
        onChanged();
        return this;
      }

      private float lYR_ ;
      /**
       * <code>optional float LYR = 8;</code>
       *
       * <pre>
       *去年度净利润
       * </pre>
       */
      public boolean hasLYR() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional float LYR = 8;</code>
       *
       * <pre>
       *去年度净利润
       * </pre>
       */
      public float getLYR() {
        return lYR_;
      }
      /**
       * <code>optional float LYR = 8;</code>
       *
       * <pre>
       *去年度净利润
       * </pre>
       */
      public Builder setLYR(float value) {
        bitField0_ |= 0x00000080;
        lYR_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float LYR = 8;</code>
       *
       * <pre>
       *去年度净利润
       * </pre>
       */
      public Builder clearLYR() {
        bitField0_ = (bitField0_ & ~0x00000080);
        lYR_ = 0F;
        onChanged();
        return this;
      }

      private float tTM_ ;
      /**
       * <code>optional float TTM = 9;</code>
       *
       * <pre>
       *近12个月净利润
       * </pre>
       */
      public boolean hasTTM() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional float TTM = 9;</code>
       *
       * <pre>
       *近12个月净利润
       * </pre>
       */
      public float getTTM() {
        return tTM_;
      }
      /**
       * <code>optional float TTM = 9;</code>
       *
       * <pre>
       *近12个月净利润
       * </pre>
       */
      public Builder setTTM(float value) {
        bitField0_ |= 0x00000100;
        tTM_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float TTM = 9;</code>
       *
       * <pre>
       *近12个月净利润
       * </pre>
       */
      public Builder clearTTM() {
        bitField0_ = (bitField0_ & ~0x00000100);
        tTM_ = 0F;
        onChanged();
        return this;
      }

      private float mRQ_ ;
      /**
       * <code>optional float MRQ = 10;</code>
       *
       * <pre>
       *最新年化净利润
       * </pre>
       */
      public boolean hasMRQ() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional float MRQ = 10;</code>
       *
       * <pre>
       *最新年化净利润
       * </pre>
       */
      public float getMRQ() {
        return mRQ_;
      }
      /**
       * <code>optional float MRQ = 10;</code>
       *
       * <pre>
       *最新年化净利润
       * </pre>
       */
      public Builder setMRQ(float value) {
        bitField0_ |= 0x00000200;
        mRQ_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float MRQ = 10;</code>
       *
       * <pre>
       *最新年化净利润
       * </pre>
       */
      public Builder clearMRQ() {
        bitField0_ = (bitField0_ & ~0x00000200);
        mRQ_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.baidu.stock.quote.protocbuf.XYAFinacialInfo)
    }

    static {
      defaultInstance = new XYAFinacialInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.baidu.stock.quote.protocbuf.XYAFinacialInfo)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_baidu_stock_quote_protocbuf_XYAFinacialInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_baidu_stock_quote_protocbuf_XYAFinacialInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025XYAFinacialInfo.proto\022\037com.baidu.stock" +
      ".quote.protocbuf\032\020StockBasic.proto\"\351\001\n\017X" +
      "YAFinacialInfo\022=\n\010security\030\001 \002(\0132+.com.b" +
      "aidu.stock.quote.protocbuf.StockBasic\022\023\n" +
      "\013totalAmount\030\002 \001(\003\022\017\n\007AAmount\030\003 \001(\003\022\021\n\tn" +
      "etAssets\030\004 \001(\002\022\023\n\013stockProfit\030\005 \001(\002\022\024\n\014s" +
      "ellAmountPS\030\006 \001(\002\022\014\n\004date\030\007 \001(\005\022\013\n\003LYR\030\010" +
      " \001(\002\022\013\n\003TTM\030\t \001(\002\022\013\n\003MRQ\030\n \001(\002B7\n\037com.ba" +
      "idu.stock.quote.protocbufB\024XYAFinacialIn" +
      "foProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.baidu.stock.quote.protocbuf.StockBasicProto.getDescriptor(),
        }, assigner);
    internal_static_com_baidu_stock_quote_protocbuf_XYAFinacialInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_baidu_stock_quote_protocbuf_XYAFinacialInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_baidu_stock_quote_protocbuf_XYAFinacialInfo_descriptor,
        new java.lang.String[] { "Security", "TotalAmount", "AAmount", "NetAssets", "StockProfit", "SellAmountPS", "Date", "LYR", "TTM", "MRQ", });
    com.baidu.stock.quote.protocbuf.StockBasicProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
